catalogMode: prefer
ignoreWorkspaceRootCheck: true
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - playground
  - docs
  - packages/*
  - examples/*

catalog:
  '@antfu/eslint-config': ^6.5.1
  '@antfu/ni': ^28.0.0
  '@antfu/utils': ^9.3.0
  '@types/node': ^24.10.2
  bumpp: ^10.3.2
  cac: ^6.7.14
  chokidar: ^5.0.0
  eslint: ^9.39.1
  lint-staged: ^16.2.7
  pnpm: ^10.25.0
  scule: ^1.3.0
  simple-git-hooks: ^2.13.1
  taze: ^19.9.2
  tinyglobby: ^0.2.15
  tsdown: ^0.17.2
  tsx: ^4.21.0
  typescript: ^5.9.3
  vite: ^7.2.7
  vitest: ^4.0.15

onlyBuiltDependencies:
  - esbuild
  - simple-git-hooks
