// This file is generated by `vscode-ext-gen`. Do not modify manually.
// @see https://github.com/antfu/vscode-ext-gen

// Meta info
export const publisher = "lokalise"
export const name = "i18n-ally"
export const version = "2.12.0"
export const displayName = "i18n Ally"
export const description = "🌍 All in one i18n extension for VS Code"
export const extensionName = `${publisher}.${name}`

/**
 * Type union of all commands
 */
export type CommandId = 
  | "i18n-ally.config-locales"
  | "i18n-ally.config-locales-auto"
  | "i18n-ally.config-display-language"
  | "i18n-ally.config-source-language"
  | "i18n-ally.set-display-language"
  | "i18n-ally.set-source-language"
  | "i18n-ally.copy-key"
  | "i18n-ally.translate-key"
  | "i18n-ally.edit-key"
  | "i18n-ally.open-key"
  | "i18n-ally.delete-key"
  | "i18n-ally.rename-key"
  | "i18n-ally.extract-text"
  | "i18n-ally.extract-hard-strings-batch"
  | "i18n-ally.detect_hard_strings"
  | "i18n-ally.open-url"
  | "i18n-ally.fulfill-keys"
  | "i18n-ally.refresh-usage"
  | "i18n-ally.support"
  | "i18n-ally.locale-visibility-show"
  | "i18n-ally.locale-visibility-hide"
  | "i18n-ally.new-key"
  | "i18n-ally.duplicate-key"
  | "i18n-ally.mark-key-as-in-use"
  | "i18n-ally.open-in-editor"
  | "i18n-ally.open-editor"
  | "i18n-ally.review.comment"
  | "i18n-ally.review.approve"
  | "i18n-ally.review.request-change"
  | "i18n-ally.review.edit"
  | "i18n-ally.review.resolve"
  | "i18n-ally.review.resolve-thread"
  | "i18n-ally.review.apply-translation"
  | "i18n-ally.review.apply-suggestion"
  | "i18n-ally.insert-key"
  | "i18n-ally.deepl-usage"
  | "i18n-ally.go-to-range"
  | "i18n-ally.go-to-next-usage"
  | "i18n-ally.go-to-prev-usage"
  | "i18n-ally.open-docs-hard-string"
  | "i18n-ally.extract-disable-auto-detect"
  | "i18n-ally.extract-enable-auto-detect"

/**
 * Commands map registed by `lokalise.i18n-ally`
 */
export const commands = {
  /**
   * %command.config_locales%
   * @value `i18n-ally.config-locales`
   */
  configLocales: "i18n-ally.config-locales",
  /**
   * %command.config_locales_auto%
   * @value `i18n-ally.config-locales-auto`
   */
  configLocalesAuto: "i18n-ally.config-locales-auto",
  /**
   * %command.config_display_language%
   * @value `i18n-ally.config-display-language`
   */
  configDisplayLanguage: "i18n-ally.config-display-language",
  /**
   * %command.config_source_language%
   * @value `i18n-ally.config-source-language`
   */
  configSourceLanguage: "i18n-ally.config-source-language",
  /**
   * %command.set_display_language%
   * @value `i18n-ally.set-display-language`
   */
  setDisplayLanguage: "i18n-ally.set-display-language",
  /**
   * %command.set_source_language%
   * @value `i18n-ally.set-source-language`
   */
  setSourceLanguage: "i18n-ally.set-source-language",
  /**
   * %command.copy_key%
   * @value `i18n-ally.copy-key`
   */
  copyKey: "i18n-ally.copy-key",
  /**
   * %command.translate_key%
   * @value `i18n-ally.translate-key`
   */
  translateKey: "i18n-ally.translate-key",
  /**
   * %command.edit_key%
   * @value `i18n-ally.edit-key`
   */
  editKey: "i18n-ally.edit-key",
  /**
   * %command.open_key%
   * @value `i18n-ally.open-key`
   */
  openKey: "i18n-ally.open-key",
  /**
   * %command.delete_key%
   * @value `i18n-ally.delete-key`
   */
  deleteKey: "i18n-ally.delete-key",
  /**
   * %command.rename_key%
   * @value `i18n-ally.rename-key`
   */
  renameKey: "i18n-ally.rename-key",
  /**
   * %refactor.extract_text%
   * @value `i18n-ally.extract-text`
   */
  extractText: "i18n-ally.extract-text",
  /**
   * Extract all hard-coded strings (experimental)
   * @value `i18n-ally.extract-hard-strings-batch`
   */
  extractHardStringsBatch: "i18n-ally.extract-hard-strings-batch",
  /**
   * Detect hard-coded strings in current file (experimental)
   * @value `i18n-ally.detect_hard_strings`
   */
  detectHardStrings: "i18n-ally.detect_hard_strings",
  /**
   * %command.open_url%
   * @value `i18n-ally.open-url`
   */
  openUrl: "i18n-ally.open-url",
  /**
   * %command.fulfill_keys%
   * @value `i18n-ally.fulfill-keys`
   */
  fulfillKeys: "i18n-ally.fulfill-keys",
  /**
   * %command.refresh_usage%
   * @value `i18n-ally.refresh-usage`
   */
  refreshUsage: "i18n-ally.refresh-usage",
  /**
   * %feedback.support%
   * @value `i18n-ally.support`
   */
  support: "i18n-ally.support",
  /**
   * %command.locale_visibility_show%
   * @value `i18n-ally.locale-visibility-show`
   */
  localeVisibilityShow: "i18n-ally.locale-visibility-show",
  /**
   * %command.locale_visibility_hide%
   * @value `i18n-ally.locale-visibility-hide`
   */
  localeVisibilityHide: "i18n-ally.locale-visibility-hide",
  /**
   * %command.new_key%
   * @value `i18n-ally.new-key`
   */
  newKey: "i18n-ally.new-key",
  /**
   * %command.duplicate_key%
   * @value `i18n-ally.duplicate-key`
   */
  duplicateKey: "i18n-ally.duplicate-key",
  /**
   * %command.mark_key_as_in_use%
   * @value `i18n-ally.mark-key-as-in-use`
   */
  markKeyAsInUse: "i18n-ally.mark-key-as-in-use",
  /**
   * %command.open_in_editor%
   * @value `i18n-ally.open-in-editor`
   */
  openInEditor: "i18n-ally.open-in-editor",
  /**
   * %command.open_editor%
   * @value `i18n-ally.open-editor`
   */
  openEditor: "i18n-ally.open-editor",
  /**
   * %review.leave_comment%
   * @value `i18n-ally.review.comment`
   */
  reviewComment: "i18n-ally.review.comment",
  /**
   * %review.approve%
   * @value `i18n-ally.review.approve`
   */
  reviewApprove: "i18n-ally.review.approve",
  /**
   * %review.request_change%
   * @value `i18n-ally.review.request-change`
   */
  reviewRequestChange: "i18n-ally.review.request-change",
  /**
   * %review.edit%
   * @value `i18n-ally.review.edit`
   */
  reviewEdit: "i18n-ally.review.edit",
  /**
   * %review.resolve%
   * @value `i18n-ally.review.resolve`
   */
  reviewResolve: "i18n-ally.review.resolve",
  /**
   * %review.resolve_all%
   * @value `i18n-ally.review.resolve-thread`
   */
  reviewResolveThread: "i18n-ally.review.resolve-thread",
  /**
   * %review.apply_translation_candidate%
   * @value `i18n-ally.review.apply-translation`
   */
  reviewApplyTranslation: "i18n-ally.review.apply-translation",
  /**
   * %review.apply_suggestion%
   * @value `i18n-ally.review.apply-suggestion`
   */
  reviewApplySuggestion: "i18n-ally.review.apply-suggestion",
  /**
   * %command.insert_key%
   * @value `i18n-ally.insert-key`
   */
  insertKey: "i18n-ally.insert-key",
  /**
   * %command.deepl_usage%
   * @value `i18n-ally.deepl-usage`
   */
  deeplUsage: "i18n-ally.deepl-usage",
  /**
   * %command.go_to_range%
   * @value `i18n-ally.go-to-range`
   */
  goToRange: "i18n-ally.go-to-range",
  /**
   * %command.go_to_next_usage%
   * @value `i18n-ally.go-to-next-usage`
   */
  goToNextUsage: "i18n-ally.go-to-next-usage",
  /**
   * %command.go_to_prev_usage%
   * @value `i18n-ally.go-to-prev-usage`
   */
  goToPrevUsage: "i18n-ally.go-to-prev-usage",
  /**
   * %command.show_docs%
   * @value `i18n-ally.open-docs-hard-string`
   */
  openDocsHardString: "i18n-ally.open-docs-hard-string",
  /**
   * %command.extract.disable-auto-detect%
   * @value `i18n-ally.extract-disable-auto-detect`
   */
  extractDisableAutoDetect: "i18n-ally.extract-disable-auto-detect",
  /**
   * %command.extract.enable-auto-detect%
   * @value `i18n-ally.extract-enable-auto-detect`
   */
  extractEnableAutoDetect: "i18n-ally.extract-enable-auto-detect",
} satisfies Record<string, CommandId>

/**
 * Type union of all configs
 */
export type ConfigKey = 
  | "i18n-ally.disabled"
  | "i18n-ally.autoDetection"
  | "i18n-ally.localesPaths"
  | "i18n-ally.encoding"
  | "i18n-ally.sourceLanguage"
  | "i18n-ally.displayLanguage"
  | "i18n-ally.ignoredLocales"
  | "i18n-ally.keystyle"
  | "i18n-ally.dirStructure"
  | "i18n-ally.annotations"
  | "i18n-ally.annotationInPlace"
  | "i18n-ally.annotationMaxLength"
  | "i18n-ally.annotationDelimiter"
  | "i18n-ally.includeSubfolders"
  | "i18n-ally.fullReloadOnChanged"
  | "i18n-ally.showFlags"
  | "i18n-ally.enabledFrameworks"
  | "i18n-ally.enabledParsers"
  | "i18n-ally.keysInUse"
  | "i18n-ally.sortKeys"
  | "i18n-ally.sortCompare"
  | "i18n-ally.sortLocale"
  | "i18n-ally.preferredDelimiter"
  | "i18n-ally.readonly"
  | "i18n-ally.keepFulfilled"
  | "i18n-ally.localeCountryMap"
  | "i18n-ally.indent"
  | "i18n-ally.disablePathParsing"
  | "i18n-ally.tabStyle"
  | "i18n-ally.namespace"
  | "i18n-ally.pathMatcher"
  | "i18n-ally.languageTagSystem"
  | "i18n-ally.ignoreFiles"
  | "i18n-ally.theme.annotation"
  | "i18n-ally.theme.annotationMissing"
  | "i18n-ally.theme.annotationBorder"
  | "i18n-ally.theme.annotationMissingBorder"
  | "i18n-ally.regex.key"
  | "i18n-ally.regex.usageMatch"
  | "i18n-ally.regex.usageMatchAppend"
  | "i18n-ally.refactor.templates"
  | "i18n-ally.translate.saveAsCandidates"
  | "i18n-ally.translate.fallbackToKey"
  | "i18n-ally.translate.engines"
  | "i18n-ally.translate.parallels"
  | "i18n-ally.translate.promptSource"
  | "i18n-ally.translate.overrideExisting"
  | "i18n-ally.translate.google.apiKey"
  | "i18n-ally.translate.deepl.apiKey"
  | "i18n-ally.translate.baidu.appid"
  | "i18n-ally.translate.baidu.apiSecret"
  | "i18n-ally.translate.deepl.enableLog"
  | "i18n-ally.translate.deepl.useFreeApiEntry"
  | "i18n-ally.translate.libre.apiRoot"
  | "i18n-ally.translate.openai.apiKey"
  | "i18n-ally.translate.openai.apiRoot"
  | "i18n-ally.translate.openai.apiModel"
  | "i18n-ally.usage.scanningIgnore"
  | "i18n-ally.usage.derivedKeyRules"
  | "i18n-ally.frameworks.ruby-rails.scopeRoot"
  | "i18n-ally.parsers.typescript.tsNodePath"
  | "i18n-ally.parsers.typescript.compilerOptions"
  | "i18n-ally.parsers.extendFileExtensions"
  | "i18n-ally.review.enabled"
  | "i18n-ally.review.gutters"
  | "i18n-ally.review.user.name"
  | "i18n-ally.review.user.email"
  | "i18n-ally.review.removeCommentOnResolved"
  | "i18n-ally.editor.preferEditor"
  | "i18n-ally.extract.keygenStrategy"
  | "i18n-ally.extract.keygenStyle"
  | "i18n-ally.extract.keyPrefix"
  | "i18n-ally.extract.keyMaxLength"
  | "i18n-ally.extract.targetPickingStrategy"
  | "i18n-ally.extract.parsers.html"
  | "i18n-ally.extract.parsers.babel"
  | "i18n-ally.extract.autoDetect"
  | "i18n-ally.extract.ignored"
  | "i18n-ally.extract.ignoredByFiles"
  | "i18n-ally.parserOptions"
  | "i18n-ally.defaultNamespace"
  | "i18n-ally.derivedKeyRules"
  | "i18n-ally.filenameMatchRegex"
  | "i18n-ally.fileNamespace"
  | "i18n-ally.keyMatchRegex"
  | "vue-i18n-ally.localesPaths"
  | "vue-i18n-ally.encoding"
  | "vue-i18n-ally.sourceLanguage"
  | "vue-i18n-ally.displayLanguage"
  | "vue-i18n-ally.ignoredLocales"
  | "vue-i18n-ally.keystyle"
  | "vue-i18n-ally.dirStructure"
  | "vue-i18n-ally.annotations"
  | "vue-i18n-ally.annotationMaxLength"
  | "vue-i18n-ally.annotationDelimiter"
  | "vue-i18n-ally.filenameMatchRegex"
  | "vue-i18n-ally.includeSubfolders"
  | "vue-i18n-ally.fullReloadOnChanged"
  | "vue-i18n-ally.sortKeys"
  | "vue-i18n-ally.preferredDelimiter"
  | "vue-i18n-ally.readonly"

/**
 * Configs map registed by `lokalise.i18n-ally`
 */
export const configs = {
  /**
   * %config.disabled%
   * @key `i18n-ally.disabled`
   * @default `false`
   * @type `boolean`
   */
  disabled: "i18n-ally.disabled",
  /**
   * %config.auto_detection%
   * @key `i18n-ally.autoDetection`
   * @default `true`
   * @type `boolean`
   */
  autoDetection: "i18n-ally.autoDetection",
  /**
   * %config.locales_paths%
   * @key `i18n-ally.localesPaths`
   * @default `undefined`
   * @type `string,array`
   */
  localesPaths: "i18n-ally.localesPaths",
  /**
   * %config.encoding%
   * @key `i18n-ally.encoding`
   * @default `"utf-8"`
   * @type `string`
   */
  encoding: "i18n-ally.encoding",
  /**
   * %config.source_language%
   * @key `i18n-ally.sourceLanguage`
   * @default `undefined`
   * @type `string`
   */
  sourceLanguage: "i18n-ally.sourceLanguage",
  /**
   * %config.display_language%
   * @key `i18n-ally.displayLanguage`
   * @default `undefined`
   * @type `string`
   */
  displayLanguage: "i18n-ally.displayLanguage",
  /**
   * %config.ignored_locales%
   * @key `i18n-ally.ignoredLocales`
   * @default `undefined`
   * @type `array`
   */
  ignoredLocales: "i18n-ally.ignoredLocales",
  /**
   * %config.keystyle%
   * @key `i18n-ally.keystyle`
   * @default `undefined`
   * @type `string`
   */
  keystyle: "i18n-ally.keystyle",
  /**
   * %config.dir_structure%
   * @key `i18n-ally.dirStructure`
   * @default `undefined`
   * @type `string`
   */
  dirStructure: "i18n-ally.dirStructure",
  /**
   * %config.annotations%
   * @key `i18n-ally.annotations`
   * @default `true`
   * @type `boolean`
   */
  annotations: "i18n-ally.annotations",
  /**
   * %config.annotation_in_place%
   * @key `i18n-ally.annotationInPlace`
   * @default `true`
   * @type `boolean`
   */
  annotationInPlace: "i18n-ally.annotationInPlace",
  /**
   * %config.annotation_max_length%
   * @key `i18n-ally.annotationMaxLength`
   * @default `40`
   * @type `number`
   */
  annotationMaxLength: "i18n-ally.annotationMaxLength",
  /**
   * %config.annotation_delimiter%
   * @key `i18n-ally.annotationDelimiter`
   * @default `"·"`
   * @type `string`
   */
  annotationDelimiter: "i18n-ally.annotationDelimiter",
  /**
   * %config.include_subfolders%
   * @key `i18n-ally.includeSubfolders`
   * @default `true`
   * @type `boolean`
   */
  includeSubfolders: "i18n-ally.includeSubfolders",
  /**
   * %config.full_reload_on_changed%
   * @key `i18n-ally.fullReloadOnChanged`
   * @default `false`
   * @type `boolean`
   */
  fullReloadOnChanged: "i18n-ally.fullReloadOnChanged",
  /**
   * %config.show_flags%
   * @key `i18n-ally.showFlags`
   * @default `true`
   * @type `boolean`
   */
  showFlags: "i18n-ally.showFlags",
  /**
   * %config.enabled_frameworks%
   * @key `i18n-ally.enabledFrameworks`
   * @default `undefined`
   * @type `array`
   */
  enabledFrameworks: "i18n-ally.enabledFrameworks",
  /**
   * %config.enabled_parsers%
   * @key `i18n-ally.enabledParsers`
   * @default `undefined`
   * @type `array`
   */
  enabledParsers: "i18n-ally.enabledParsers",
  /**
   * %config.keys_in_use%
   * @key `i18n-ally.keysInUse`
   * @default `undefined`
   * @type `array`
   */
  keysInUse: "i18n-ally.keysInUse",
  /**
   * %config.sort_keys%
   * @key `i18n-ally.sortKeys`
   * @default `false`
   * @type `boolean`
   */
  sortKeys: "i18n-ally.sortKeys",
  /**
   * %config.sort_compare%
   * @key `i18n-ally.sortCompare`
   * @default `"binary"`
   * @type `string`
   */
  sortCompare: "i18n-ally.sortCompare",
  /**
   * %config.sort_locale%
   * @key `i18n-ally.sortLocale`
   * @default `undefined`
   * @type `string`
   */
  sortLocale: "i18n-ally.sortLocale",
  /**
   * %config.preferred_delimiter%
   * @key `i18n-ally.preferredDelimiter`
   * @default `"-"`
   * @type `string`
   */
  preferredDelimiter: "i18n-ally.preferredDelimiter",
  /**
   * %config.readonly%
   * @key `i18n-ally.readonly`
   * @default `false`
   * @type `boolean`
   */
  readonly: "i18n-ally.readonly",
  /**
   * %config.keep_fulfill%
   * @key `i18n-ally.keepFulfilled`
   * @default `false`
   * @type `boolean`
   */
  keepFulfilled: "i18n-ally.keepFulfilled",
  /**
   * %config.locale_country_map%
   * @key `i18n-ally.localeCountryMap`
   * @default `{}`
   * @type `object`
   */
  localeCountryMap: "i18n-ally.localeCountryMap",
  /**
   * %config.indent%
   * @key `i18n-ally.indent`
   * @default `2`
   * @type `number`
   */
  indent: "i18n-ally.indent",
  /**
   * %config.disable_path_parsing%
   * @key `i18n-ally.disablePathParsing`
   * @default `false`
   * @type `boolean`
   */
  disablePathParsing: "i18n-ally.disablePathParsing",
  /**
   * %config.tab_style%
   * @key `i18n-ally.tabStyle`
   * @default `"space"`
   * @type `string`
   */
  tabStyle: "i18n-ally.tabStyle",
  /**
   * %config.namespace%
   * @key `i18n-ally.namespace`
   * @default `undefined`
   * @type `boolean`
   */
  namespace: "i18n-ally.namespace",
  /**
   * %config.path_matcher%
   * @key `i18n-ally.pathMatcher`
   * @default `undefined`
   * @type `string`
   */
  pathMatcher: "i18n-ally.pathMatcher",
  /**
   * %config.language_tag_system%
   * @key `i18n-ally.languageTagSystem`
   * @default `"bcp47"`
   * @type `string`
   */
  languageTagSystem: "i18n-ally.languageTagSystem",
  /**
   * %config.ignore_files%
   * @key `i18n-ally.ignoreFiles`
   * @default `undefined`
   * @type `array`
   */
  ignoreFiles: "i18n-ally.ignoreFiles",
  /**
   * 
   * @key `i18n-ally.theme.annotation`
   * @default `"rgba(153, 153, 153, .8)"`
   * @type `string`
   */
  themeAnnotation: "i18n-ally.theme.annotation",
  /**
   * 
   * @key `i18n-ally.theme.annotationMissing`
   * @default `"rgba(153, 153, 153, .3)"`
   * @type `string`
   */
  themeAnnotationMissing: "i18n-ally.theme.annotationMissing",
  /**
   * 
   * @key `i18n-ally.theme.annotationBorder`
   * @default `"rgba(153, 153, 153, .2)"`
   * @type `string`
   */
  themeAnnotationBorder: "i18n-ally.theme.annotationBorder",
  /**
   * 
   * @key `i18n-ally.theme.annotationMissingBorder`
   * @default `"rgba(153, 153, 153, .2)"`
   * @type `string`
   */
  themeAnnotationMissingBorder: "i18n-ally.theme.annotationMissingBorder",
  /**
   * %config.regex_key%
   * @key `i18n-ally.regex.key`
   * @default `undefined`
   * @type `string`
   */
  regexKey: "i18n-ally.regex.key",
  /**
   * %config.regex_usage_match%
   * @key `i18n-ally.regex.usageMatch`
   * @default `undefined`
   * @type `array`
   */
  regexUsageMatch: "i18n-ally.regex.usageMatch",
  /**
   * %config.regex_usage_match_append%
   * @key `i18n-ally.regex.usageMatchAppend`
   * @default `undefined`
   * @type `array`
   */
  regexUsageMatchAppend: "i18n-ally.regex.usageMatchAppend",
  /**
   * %config.refactor_templates%
   * @key `i18n-ally.refactor.templates`
   * @default `undefined`
   * @type `array`
   */
  refactorTemplates: "i18n-ally.refactor.templates",
  /**
   * %config.translate_save_as_candidates%
   * @key `i18n-ally.translate.saveAsCandidates`
   * @default `false`
   * @type `boolean`
   */
  translateSaveAsCandidates: "i18n-ally.translate.saveAsCandidates",
  /**
   * %config.translate.fallbackToKey%
   * @key `i18n-ally.translate.fallbackToKey`
   * @default `false`
   * @type `boolean`
   */
  translateFallbackToKey: "i18n-ally.translate.fallbackToKey",
  /**
   * %config.translate.engines%
   * @key `i18n-ally.translate.engines`
   * @default `["google"]`
   * @type `array`
   */
  translateEngines: "i18n-ally.translate.engines",
  /**
   * %config.translate.parallels%
   * @key `i18n-ally.translate.parallels`
   * @default `5`
   * @type `number`
   */
  translateParallels: "i18n-ally.translate.parallels",
  /**
   * %config.prompt_translating_source%
   * @key `i18n-ally.translate.promptSource`
   * @default `false`
   * @type `boolean`
   */
  translatePromptSource: "i18n-ally.translate.promptSource",
  /**
   * %config.translate_override_existing%
   * @key `i18n-ally.translate.overrideExisting`
   * @default `false`
   * @type `boolean`
   */
  translateOverrideExisting: "i18n-ally.translate.overrideExisting",
  /**
   * %config.google_api_key%
   * @key `i18n-ally.translate.google.apiKey`
   * @default `null`
   * @type `string`
   */
  translateGoogleApiKey: "i18n-ally.translate.google.apiKey",
  /**
   * %config.deepl_api_key%
   * @key `i18n-ally.translate.deepl.apiKey`
   * @default `null`
   * @type `string`
   */
  translateDeeplApiKey: "i18n-ally.translate.deepl.apiKey",
  /**
   * %config.baidu_appid%
   * @key `i18n-ally.translate.baidu.appid`
   * @default `null`
   * @type `string`
   */
  translateBaiduAppid: "i18n-ally.translate.baidu.appid",
  /**
   * %config.baidu_app_secret%
   * @key `i18n-ally.translate.baidu.apiSecret`
   * @default `null`
   * @type `string`
   */
  translateBaiduApiSecret: "i18n-ally.translate.baidu.apiSecret",
  /**
   * %config.deepl_log%
   * @key `i18n-ally.translate.deepl.enableLog`
   * @default `false`
   * @type `boolean`
   */
  translateDeeplEnableLog: "i18n-ally.translate.deepl.enableLog",
  /**
   * %config.deepl_use_free_api_entry%
   * @key `i18n-ally.translate.deepl.useFreeApiEntry`
   * @default `false`
   * @type `boolean`
   */
  translateDeeplUseFreeApiEntry: "i18n-ally.translate.deepl.useFreeApiEntry",
  /**
   * %config.libretranslate_api_root%
   * @key `i18n-ally.translate.libre.apiRoot`
   * @default `"http://localhost:5000"`
   * @type `string`
   */
  translateLibreApiRoot: "i18n-ally.translate.libre.apiRoot",
  /**
   * %config.openai_api_key%
   * @key `i18n-ally.translate.openai.apiKey`
   * @default `null`
   * @type `string`
   */
  translateOpenaiApiKey: "i18n-ally.translate.openai.apiKey",
  /**
   * %config.openai_api_root%
   * @key `i18n-ally.translate.openai.apiRoot`
   * @default `"https://api.openai.com"`
   * @type `string`
   */
  translateOpenaiApiRoot: "i18n-ally.translate.openai.apiRoot",
  /**
   * %config.openai_api_model%
   * @key `i18n-ally.translate.openai.apiModel`
   * @default `"gpt-3.5-turbo"`
   * @type `string`
   */
  translateOpenaiApiModel: "i18n-ally.translate.openai.apiModel",
  /**
   * %config.usage.scanning_ignore%
   * @key `i18n-ally.usage.scanningIgnore`
   * @default `undefined`
   * @type `array`
   */
  usageScanningIgnore: "i18n-ally.usage.scanningIgnore",
  /**
   * %config.derived_keys%
   * @key `i18n-ally.usage.derivedKeyRules`
   * @default `null`
   * @type `array`
   */
  usageDerivedKeyRules: "i18n-ally.usage.derivedKeyRules",
  /**
   * 
   * @key `i18n-ally.frameworks.ruby-rails.scopeRoot`
   * @default `"app/views"`
   * @type `string`
   */
  frameworksRubyRailsScopeRoot: "i18n-ally.frameworks.ruby-rails.scopeRoot",
  /**
   * 
   * @key `i18n-ally.parsers.typescript.tsNodePath`
   * @default `"node_modules/ts-node/dist/bin.js"`
   * @type `string`
   */
  parsersTypescriptTsNodePath: "i18n-ally.parsers.typescript.tsNodePath",
  /**
   * 
   * @key `i18n-ally.parsers.typescript.compilerOptions`
   * @default `{}`
   * @type `object`
   */
  parsersTypescriptCompilerOptions: "i18n-ally.parsers.typescript.compilerOptions",
  /**
   * 
   * @key `i18n-ally.parsers.extendFileExtensions`
   * @default `{}`
   * @type `object`
   */
  parsersExtendFileExtensions: "i18n-ally.parsers.extendFileExtensions",
  /**
   * %config.review_enabled%
   * @key `i18n-ally.review.enabled`
   * @default `true`
   * @type `boolean`
   */
  reviewEnabled: "i18n-ally.review.enabled",
  /**
   * %config.review_gutters%
   * @key `i18n-ally.review.gutters`
   * @default `true`
   * @type `boolean`
   */
  reviewGutters: "i18n-ally.review.gutters",
  /**
   * %config.review_username%
   * @key `i18n-ally.review.user.name`
   * @default `undefined`
   * @type `string`
   */
  reviewUserName: "i18n-ally.review.user.name",
  /**
   * %config.review_email%
   * @key `i18n-ally.review.user.email`
   * @default `undefined`
   * @type `string`
   */
  reviewUserEmail: "i18n-ally.review.user.email",
  /**
   * %config.review_remove_on_resolved%
   * @key `i18n-ally.review.removeCommentOnResolved`
   * @default `false`
   * @type `boolean`
   */
  reviewRemoveCommentOnResolved: "i18n-ally.review.removeCommentOnResolved",
  /**
   * %config.editor_prefer_editor%
   * @key `i18n-ally.editor.preferEditor`
   * @default `false`
   * @type `boolean`
   */
  editorPreferEditor: "i18n-ally.editor.preferEditor",
  /**
   * %config.keygen_strategy%
   * @key `i18n-ally.extract.keygenStrategy`
   * @default `"slug"`
   * @type `string`
   */
  extractKeygenStrategy: "i18n-ally.extract.keygenStrategy",
  /**
   * %config.keygen_style%
   * @key `i18n-ally.extract.keygenStyle`
   * @default `"default"`
   * @type `string`
   */
  extractKeygenStyle: "i18n-ally.extract.keygenStyle",
  /**
   * %config.key_prefix%
   * @key `i18n-ally.extract.keyPrefix`
   * @default `""`
   * @type `string`
   */
  extractKeyPrefix: "i18n-ally.extract.keyPrefix",
  /**
   * %config.key_max_length%
   * @key `i18n-ally.extract.keyMaxLength`
   * @default `null`
   * @type `number`
   */
  extractKeyMaxLength: "i18n-ally.extract.keyMaxLength",
  /**
   * %config.target_picking_strategy%
   * @key `i18n-ally.extract.targetPickingStrategy`
   * @default `"none"`
   * @type `string`
   */
  extractTargetPickingStrategy: "i18n-ally.extract.targetPickingStrategy",
  /**
   * Parser options for extracting HTML, see https://github.com/lokalise/i18n-ally/blob/master/src/extraction/parsers/options.ts
   * @key `i18n-ally.extract.parsers.html`
   * @default `{}`
   * @type `object`
   */
  extractParsersHtml: "i18n-ally.extract.parsers.html",
  /**
   * Parser options for extracting JS/TS/JSX/TSX, see https://github.com/lokalise/i18n-ally/blob/master/src/extraction/parsers/options.ts
   * @key `i18n-ally.extract.parsers.babel`
   * @default `{}`
   * @type `object`
   */
  extractParsersBabel: "i18n-ally.extract.parsers.babel",
  /**
   * Enables hard-coded strings detection automatically whenever opening a supported file
   * @key `i18n-ally.extract.autoDetect`
   * @default `false`
   * @type `boolean`
   */
  extractAutoDetect: "i18n-ally.extract.autoDetect",
  /**
   * Strings to be ignored on hard-coded strings detection
   * @key `i18n-ally.extract.ignored`
   * @default `undefined`
   * @type `array`
   */
  extractIgnored: "i18n-ally.extract.ignored",
  /**
   * Strings to be ignored on hard-coded strings detection, by files
   * @key `i18n-ally.extract.ignoredByFiles`
   * @default `{}`
   * @type `object`
   */
  extractIgnoredByFiles: "i18n-ally.extract.ignoredByFiles",
  /**
   * 
   * @key `i18n-ally.parserOptions`
   * @default `undefined`
   * @type `object`
   */
  parserOptions: "i18n-ally.parserOptions",
  /**
   * %config.default_namespace%
   * @key `i18n-ally.defaultNamespace`
   * @default `undefined`
   * @type `string`
   */
  defaultNamespace: "i18n-ally.defaultNamespace",
  /**
   * 
   * @key `i18n-ally.derivedKeyRules`
   * @default `undefined`
   * @type `undefined`
   */
  derivedKeyRules: "i18n-ally.derivedKeyRules",
  /**
   * 
   * @key `i18n-ally.filenameMatchRegex`
   * @default `undefined`
   * @type `undefined`
   */
  filenameMatchRegex: "i18n-ally.filenameMatchRegex",
  /**
   * 
   * @key `i18n-ally.fileNamespace`
   * @default `undefined`
   * @type `undefined`
   */
  fileNamespace: "i18n-ally.fileNamespace",
  /**
   * 
   * @key `i18n-ally.keyMatchRegex`
   * @default `undefined`
   * @type `undefined`
   */
  keyMatchRegex: "i18n-ally.keyMatchRegex",
  /**
   * 
   * @key `vue-i18n-ally.localesPaths`
   * @default `undefined`
   * @type `undefined`
   */
  vueI18nAllyLocalesPaths: "vue-i18n-ally.localesPaths",
  /**
   * 
   * @key `vue-i18n-ally.encoding`
   * @default `undefined`
   * @type `undefined`
   */
  vueI18nAllyEncoding: "vue-i18n-ally.encoding",
  /**
   * 
   * @key `vue-i18n-ally.sourceLanguage`
   * @default `undefined`
   * @type `undefined`
   */
  vueI18nAllySourceLanguage: "vue-i18n-ally.sourceLanguage",
  /**
   * 
   * @key `vue-i18n-ally.displayLanguage`
   * @default `undefined`
   * @type `undefined`
   */
  vueI18nAllyDisplayLanguage: "vue-i18n-ally.displayLanguage",
  /**
   * 
   * @key `vue-i18n-ally.ignoredLocales`
   * @default `undefined`
   * @type `undefined`
   */
  vueI18nAllyIgnoredLocales: "vue-i18n-ally.ignoredLocales",
  /**
   * 
   * @key `vue-i18n-ally.keystyle`
   * @default `undefined`
   * @type `undefined`
   */
  vueI18nAllyKeystyle: "vue-i18n-ally.keystyle",
  /**
   * 
   * @key `vue-i18n-ally.dirStructure`
   * @default `undefined`
   * @type `undefined`
   */
  vueI18nAllyDirStructure: "vue-i18n-ally.dirStructure",
  /**
   * 
   * @key `vue-i18n-ally.annotations`
   * @default `undefined`
   * @type `undefined`
   */
  vueI18nAllyAnnotations: "vue-i18n-ally.annotations",
  /**
   * 
   * @key `vue-i18n-ally.annotationMaxLength`
   * @default `undefined`
   * @type `undefined`
   */
  vueI18nAllyAnnotationMaxLength: "vue-i18n-ally.annotationMaxLength",
  /**
   * 
   * @key `vue-i18n-ally.annotationDelimiter`
   * @default `undefined`
   * @type `undefined`
   */
  vueI18nAllyAnnotationDelimiter: "vue-i18n-ally.annotationDelimiter",
  /**
   * 
   * @key `vue-i18n-ally.filenameMatchRegex`
   * @default `undefined`
   * @type `undefined`
   */
  vueI18nAllyFilenameMatchRegex: "vue-i18n-ally.filenameMatchRegex",
  /**
   * 
   * @key `vue-i18n-ally.includeSubfolders`
   * @default `undefined`
   * @type `undefined`
   */
  vueI18nAllyIncludeSubfolders: "vue-i18n-ally.includeSubfolders",
  /**
   * 
   * @key `vue-i18n-ally.fullReloadOnChanged`
   * @default `undefined`
   * @type `undefined`
   */
  vueI18nAllyFullReloadOnChanged: "vue-i18n-ally.fullReloadOnChanged",
  /**
   * 
   * @key `vue-i18n-ally.sortKeys`
   * @default `undefined`
   * @type `undefined`
   */
  vueI18nAllySortKeys: "vue-i18n-ally.sortKeys",
  /**
   * 
   * @key `vue-i18n-ally.preferredDelimiter`
   * @default `undefined`
   * @type `undefined`
   */
  vueI18nAllyPreferredDelimiter: "vue-i18n-ally.preferredDelimiter",
  /**
   * 
   * @key `vue-i18n-ally.readonly`
   * @default `undefined`
   * @type `undefined`
   */
  vueI18nAllyReadonly: "vue-i18n-ally.readonly",
} satisfies Record<string, ConfigKey>

export const configDefaults = {
  "i18n-ally.disabled": false,
  "i18n-ally.autoDetection": true,
  "i18n-ally.localesPaths": undefined,
  "i18n-ally.encoding": "utf-8",
  "i18n-ally.sourceLanguage": undefined,
  "i18n-ally.displayLanguage": undefined,
  "i18n-ally.ignoredLocales": undefined,
  "i18n-ally.keystyle": undefined,
  "i18n-ally.dirStructure": undefined,
  "i18n-ally.annotations": true,
  "i18n-ally.annotationInPlace": true,
  "i18n-ally.annotationMaxLength": 40,
  "i18n-ally.annotationDelimiter": "·",
  "i18n-ally.includeSubfolders": true,
  "i18n-ally.fullReloadOnChanged": false,
  "i18n-ally.showFlags": true,
  "i18n-ally.enabledFrameworks": undefined,
  "i18n-ally.enabledParsers": undefined,
  "i18n-ally.keysInUse": undefined,
  "i18n-ally.sortKeys": false,
  "i18n-ally.sortCompare": "binary",
  "i18n-ally.sortLocale": undefined,
  "i18n-ally.preferredDelimiter": "-",
  "i18n-ally.readonly": false,
  "i18n-ally.keepFulfilled": false,
  "i18n-ally.localeCountryMap": {},
  "i18n-ally.indent": 2,
  "i18n-ally.disablePathParsing": false,
  "i18n-ally.tabStyle": "space",
  "i18n-ally.namespace": undefined,
  "i18n-ally.pathMatcher": undefined,
  "i18n-ally.languageTagSystem": "bcp47",
  "i18n-ally.ignoreFiles": undefined,
  "i18n-ally.theme.annotation": "rgba(153, 153, 153, .8)",
  "i18n-ally.theme.annotationMissing": "rgba(153, 153, 153, .3)",
  "i18n-ally.theme.annotationBorder": "rgba(153, 153, 153, .2)",
  "i18n-ally.theme.annotationMissingBorder": "rgba(153, 153, 153, .2)",
  "i18n-ally.regex.key": undefined,
  "i18n-ally.regex.usageMatch": undefined,
  "i18n-ally.regex.usageMatchAppend": undefined,
  "i18n-ally.refactor.templates": undefined,
  "i18n-ally.translate.saveAsCandidates": false,
  "i18n-ally.translate.fallbackToKey": false,
  "i18n-ally.translate.engines": ["google"],
  "i18n-ally.translate.parallels": 5,
  "i18n-ally.translate.promptSource": false,
  "i18n-ally.translate.overrideExisting": false,
  "i18n-ally.translate.google.apiKey": null,
  "i18n-ally.translate.deepl.apiKey": null,
  "i18n-ally.translate.baidu.appid": null,
  "i18n-ally.translate.baidu.apiSecret": null,
  "i18n-ally.translate.deepl.enableLog": false,
  "i18n-ally.translate.deepl.useFreeApiEntry": false,
  "i18n-ally.translate.libre.apiRoot": "http://localhost:5000",
  "i18n-ally.translate.openai.apiKey": null,
  "i18n-ally.translate.openai.apiRoot": "https://api.openai.com",
  "i18n-ally.translate.openai.apiModel": "gpt-3.5-turbo",
  "i18n-ally.usage.scanningIgnore": undefined,
  "i18n-ally.usage.derivedKeyRules": null,
  "i18n-ally.frameworks.ruby-rails.scopeRoot": "app/views",
  "i18n-ally.parsers.typescript.tsNodePath": "node_modules/ts-node/dist/bin.js",
  "i18n-ally.parsers.typescript.compilerOptions": {},
  "i18n-ally.parsers.extendFileExtensions": {},
  "i18n-ally.review.enabled": true,
  "i18n-ally.review.gutters": true,
  "i18n-ally.review.user.name": undefined,
  "i18n-ally.review.user.email": undefined,
  "i18n-ally.review.removeCommentOnResolved": false,
  "i18n-ally.editor.preferEditor": false,
  "i18n-ally.extract.keygenStrategy": "slug",
  "i18n-ally.extract.keygenStyle": "default",
  "i18n-ally.extract.keyPrefix": "",
  "i18n-ally.extract.keyMaxLength": null,
  "i18n-ally.extract.targetPickingStrategy": "none",
  "i18n-ally.extract.parsers.html": {},
  "i18n-ally.extract.parsers.babel": {},
  "i18n-ally.extract.autoDetect": false,
  "i18n-ally.extract.ignored": undefined,
  "i18n-ally.extract.ignoredByFiles": {},
  "i18n-ally.parserOptions": undefined,
  "i18n-ally.defaultNamespace": undefined,
  "i18n-ally.derivedKeyRules": undefined,
  "i18n-ally.filenameMatchRegex": undefined,
  "i18n-ally.fileNamespace": undefined,
  "i18n-ally.keyMatchRegex": undefined,
  "vue-i18n-ally.localesPaths": undefined,
  "vue-i18n-ally.encoding": undefined,
  "vue-i18n-ally.sourceLanguage": undefined,
  "vue-i18n-ally.displayLanguage": undefined,
  "vue-i18n-ally.ignoredLocales": undefined,
  "vue-i18n-ally.keystyle": undefined,
  "vue-i18n-ally.dirStructure": undefined,
  "vue-i18n-ally.annotations": undefined,
  "vue-i18n-ally.annotationMaxLength": undefined,
  "vue-i18n-ally.annotationDelimiter": undefined,
  "vue-i18n-ally.filenameMatchRegex": undefined,
  "vue-i18n-ally.includeSubfolders": undefined,
  "vue-i18n-ally.fullReloadOnChanged": undefined,
  "vue-i18n-ally.sortKeys": undefined,
  "vue-i18n-ally.preferredDelimiter": undefined,
  "vue-i18n-ally.readonly": undefined,
} satisfies { [key in ConfigKey]: ConfigTypeMap[key] | null | undefined }

export interface ConfigTypeMap {
  "i18n-ally.disabled": boolean,
  "i18n-ally.autoDetection": boolean,
  "i18n-ally.localesPaths": unknown,
  "i18n-ally.encoding": string,
  "i18n-ally.sourceLanguage": string,
  "i18n-ally.displayLanguage": string,
  "i18n-ally.ignoredLocales": unknown[],
  "i18n-ally.keystyle": ("auto" | "nested" | "flat"),
  "i18n-ally.dirStructure": ("auto" | "file" | "dir"),
  "i18n-ally.annotations": boolean,
  "i18n-ally.annotationInPlace": boolean,
  "i18n-ally.annotationMaxLength": number,
  "i18n-ally.annotationDelimiter": string,
  "i18n-ally.includeSubfolders": boolean,
  "i18n-ally.fullReloadOnChanged": boolean,
  "i18n-ally.showFlags": boolean,
  "i18n-ally.enabledFrameworks": ("vue" | "react" | "vscode" | "ngx-translate" | "i18next" | "react-i18next" | "i18next-shopify" | "i18n-tag" | "flutter" | "vue-sfc" | "ember" | "chrome-ext" | "ruby-rails" | "custom" | "laravel" | "transloco" | "svelte" | "globalize" | "ui5" | "next-translate" | "php-gettext" | "general" | "lingui" | "jekyll" | "fluent-vue" | "fluent-vue-sfc" | "next-intl" | "next-international")[],
  "i18n-ally.enabledParsers": ("js" | "ts" | "json" | "json5" | "yaml" | "ini" | "po" | "php" | "properties" | "ftl")[],
  "i18n-ally.keysInUse": string[],
  "i18n-ally.sortKeys": boolean,
  "i18n-ally.sortCompare": ("binary" | "locale"),
  "i18n-ally.sortLocale": string,
  "i18n-ally.preferredDelimiter": string,
  "i18n-ally.readonly": boolean,
  "i18n-ally.keepFulfilled": boolean,
  "i18n-ally.localeCountryMap": Record<string, unknown>,
  "i18n-ally.indent": number,
  "i18n-ally.disablePathParsing": boolean,
  "i18n-ally.tabStyle": ("space" | "tab"),
  "i18n-ally.namespace": boolean,
  "i18n-ally.pathMatcher": string,
  "i18n-ally.languageTagSystem": ("bcp47" | "legacy" | "none"),
  "i18n-ally.ignoreFiles": unknown[],
  "i18n-ally.theme.annotation": string,
  "i18n-ally.theme.annotationMissing": string,
  "i18n-ally.theme.annotationBorder": string,
  "i18n-ally.theme.annotationMissingBorder": string,
  "i18n-ally.regex.key": string,
  "i18n-ally.regex.usageMatch": string[],
  "i18n-ally.regex.usageMatchAppend": string[],
  "i18n-ally.refactor.templates": Record<string, unknown>[],
  "i18n-ally.translate.saveAsCandidates": boolean,
  "i18n-ally.translate.fallbackToKey": boolean,
  "i18n-ally.translate.engines": ("google" | "google-cn" | "deepl" | "libretranslate" | "baidu" | "openai")[],
  "i18n-ally.translate.parallels": number,
  "i18n-ally.translate.promptSource": boolean,
  "i18n-ally.translate.overrideExisting": boolean,
  "i18n-ally.translate.google.apiKey": string,
  "i18n-ally.translate.deepl.apiKey": string,
  "i18n-ally.translate.baidu.appid": string,
  "i18n-ally.translate.baidu.apiSecret": string,
  "i18n-ally.translate.deepl.enableLog": boolean,
  "i18n-ally.translate.deepl.useFreeApiEntry": boolean,
  "i18n-ally.translate.libre.apiRoot": string,
  "i18n-ally.translate.openai.apiKey": string,
  "i18n-ally.translate.openai.apiRoot": string,
  "i18n-ally.translate.openai.apiModel": ("gpt-3.5-turbo" | "gpt-3.5-turbo-16k" | "gpt-3.5-turbo-0301" | "gpt-3.5-turbo-0613" | "gpt-4" | "gpt-4-0314" | "gpt-4-0613" | "gpt-4-32k" | "gpt-4-32k-0314" | "gpt-4-32k-0613"),
  "i18n-ally.usage.scanningIgnore": string[],
  "i18n-ally.usage.derivedKeyRules": string[],
  "i18n-ally.frameworks.ruby-rails.scopeRoot": string,
  "i18n-ally.parsers.typescript.tsNodePath": string,
  "i18n-ally.parsers.typescript.compilerOptions": Record<string, unknown>,
  "i18n-ally.parsers.extendFileExtensions": Record<string, unknown>,
  "i18n-ally.review.enabled": boolean,
  "i18n-ally.review.gutters": boolean,
  "i18n-ally.review.user.name": string,
  "i18n-ally.review.user.email": string,
  "i18n-ally.review.removeCommentOnResolved": boolean,
  "i18n-ally.editor.preferEditor": boolean,
  "i18n-ally.extract.keygenStrategy": ("slug" | "random" | "empty" | "source"),
  "i18n-ally.extract.keygenStyle": ("default" | "kebab-case" | "snake_case" | "camelCase" | "PascalCase" | "ALL_CAPS"),
  "i18n-ally.extract.keyPrefix": string,
  "i18n-ally.extract.keyMaxLength": number,
  "i18n-ally.extract.targetPickingStrategy": ("none" | "most-similar" | "most-similar-by-key" | "file-previous" | "global-previous"),
  "i18n-ally.extract.parsers.html": Record<string, unknown>,
  "i18n-ally.extract.parsers.babel": Record<string, unknown>,
  "i18n-ally.extract.autoDetect": boolean,
  "i18n-ally.extract.ignored": string[],
  "i18n-ally.extract.ignoredByFiles": Record<string, unknown>,
  "i18n-ally.parserOptions": Record<string, unknown>,
  "i18n-ally.defaultNamespace": string,
  "i18n-ally.derivedKeyRules": unknown,
  "i18n-ally.filenameMatchRegex": unknown,
  "i18n-ally.fileNamespace": unknown,
  "i18n-ally.keyMatchRegex": unknown,
  "vue-i18n-ally.localesPaths": unknown,
  "vue-i18n-ally.encoding": unknown,
  "vue-i18n-ally.sourceLanguage": unknown,
  "vue-i18n-ally.displayLanguage": unknown,
  "vue-i18n-ally.ignoredLocales": unknown,
  "vue-i18n-ally.keystyle": unknown,
  "vue-i18n-ally.dirStructure": unknown,
  "vue-i18n-ally.annotations": unknown,
  "vue-i18n-ally.annotationMaxLength": unknown,
  "vue-i18n-ally.annotationDelimiter": unknown,
  "vue-i18n-ally.filenameMatchRegex": unknown,
  "vue-i18n-ally.includeSubfolders": unknown,
  "vue-i18n-ally.fullReloadOnChanged": unknown,
  "vue-i18n-ally.sortKeys": unknown,
  "vue-i18n-ally.preferredDelimiter": unknown,
  "vue-i18n-ally.readonly": unknown,
}
