// This file is generated by `vscode-ext-gen`. Do not modify manually.
// @see https://github.com/antfu/vscode-ext-gen

// Meta info

import { defineConfigObject, defineConfigs } from 'reactive-vscode'

export const publisher = "lokalise"
export const name = "i18n-ally"
export const version = "2.12.0"
export const displayName = "i18n Ally"
export const description = "🌍 All in one i18n extension for VS Code"
export const extensionId = `${publisher}.${name}`

/**
 * Type union of all commands
 */
export type CommandKey = 
  | "i18n-ally.config-locales"
  | "i18n-ally.config-locales-auto"
  | "i18n-ally.config-display-language"
  | "i18n-ally.config-source-language"
  | "i18n-ally.set-display-language"
  | "i18n-ally.set-source-language"
  | "i18n-ally.copy-key"
  | "i18n-ally.translate-key"
  | "i18n-ally.edit-key"
  | "i18n-ally.open-key"
  | "i18n-ally.delete-key"
  | "i18n-ally.rename-key"
  | "i18n-ally.extract-text"
  | "i18n-ally.extract-hard-strings-batch"
  | "i18n-ally.detect_hard_strings"
  | "i18n-ally.open-url"
  | "i18n-ally.fulfill-keys"
  | "i18n-ally.refresh-usage"
  | "i18n-ally.support"
  | "i18n-ally.locale-visibility-show"
  | "i18n-ally.locale-visibility-hide"
  | "i18n-ally.new-key"
  | "i18n-ally.duplicate-key"
  | "i18n-ally.mark-key-as-in-use"
  | "i18n-ally.open-in-editor"
  | "i18n-ally.open-editor"
  | "i18n-ally.review.comment"
  | "i18n-ally.review.approve"
  | "i18n-ally.review.request-change"
  | "i18n-ally.review.edit"
  | "i18n-ally.review.resolve"
  | "i18n-ally.review.resolve-thread"
  | "i18n-ally.review.apply-translation"
  | "i18n-ally.review.apply-suggestion"
  | "i18n-ally.insert-key"
  | "i18n-ally.deepl-usage"
  | "i18n-ally.go-to-range"
  | "i18n-ally.go-to-next-usage"
  | "i18n-ally.go-to-prev-usage"
  | "i18n-ally.open-docs-hard-string"
  | "i18n-ally.extract-disable-auto-detect"
  | "i18n-ally.extract-enable-auto-detect"

/**
 * Commands map registed by `lokalise.i18n-ally`
 */
export const commands = {
  /**
   * %command.config_locales%
   * @value `i18n-ally.config-locales`
   * @example
   * useCommand(commands.configLocales, async () => {
   *   //do actions or update config 
   * })
   */
  configLocales: "i18n-ally.config-locales",
  /**
   * %command.config_locales_auto%
   * @value `i18n-ally.config-locales-auto`
   * @example
   * useCommand(commands.configLocalesAuto, async () => {
   *   //do actions or update config 
   * })
   */
  configLocalesAuto: "i18n-ally.config-locales-auto",
  /**
   * %command.config_display_language%
   * @value `i18n-ally.config-display-language`
   * @example
   * useCommand(commands.configDisplayLanguage, async () => {
   *   //do actions or update config 
   * })
   */
  configDisplayLanguage: "i18n-ally.config-display-language",
  /**
   * %command.config_source_language%
   * @value `i18n-ally.config-source-language`
   * @example
   * useCommand(commands.configSourceLanguage, async () => {
   *   //do actions or update config 
   * })
   */
  configSourceLanguage: "i18n-ally.config-source-language",
  /**
   * %command.set_display_language%
   * @value `i18n-ally.set-display-language`
   * @example
   * useCommand(commands.setDisplayLanguage, async () => {
   *   //do actions or update config 
   * })
   */
  setDisplayLanguage: "i18n-ally.set-display-language",
  /**
   * %command.set_source_language%
   * @value `i18n-ally.set-source-language`
   * @example
   * useCommand(commands.setSourceLanguage, async () => {
   *   //do actions or update config 
   * })
   */
  setSourceLanguage: "i18n-ally.set-source-language",
  /**
   * %command.copy_key%
   * @value `i18n-ally.copy-key`
   * @example
   * useCommand(commands.copyKey, async () => {
   *   //do actions or update config 
   * })
   */
  copyKey: "i18n-ally.copy-key",
  /**
   * %command.translate_key%
   * @value `i18n-ally.translate-key`
   * @example
   * useCommand(commands.translateKey, async () => {
   *   //do actions or update config 
   * })
   */
  translateKey: "i18n-ally.translate-key",
  /**
   * %command.edit_key%
   * @value `i18n-ally.edit-key`
   * @example
   * useCommand(commands.editKey, async () => {
   *   //do actions or update config 
   * })
   */
  editKey: "i18n-ally.edit-key",
  /**
   * %command.open_key%
   * @value `i18n-ally.open-key`
   * @example
   * useCommand(commands.openKey, async () => {
   *   //do actions or update config 
   * })
   */
  openKey: "i18n-ally.open-key",
  /**
   * %command.delete_key%
   * @value `i18n-ally.delete-key`
   * @example
   * useCommand(commands.deleteKey, async () => {
   *   //do actions or update config 
   * })
   */
  deleteKey: "i18n-ally.delete-key",
  /**
   * %command.rename_key%
   * @value `i18n-ally.rename-key`
   * @example
   * useCommand(commands.renameKey, async () => {
   *   //do actions or update config 
   * })
   */
  renameKey: "i18n-ally.rename-key",
  /**
   * %refactor.extract_text%
   * @value `i18n-ally.extract-text`
   * @example
   * useCommand(commands.extractText, async () => {
   *   //do actions or update config 
   * })
   */
  extractText: "i18n-ally.extract-text",
  /**
   * Extract all hard-coded strings (experimental)
   * @value `i18n-ally.extract-hard-strings-batch`
   * @example
   * useCommand(commands.extractHardStringsBatch, async () => {
   *   //do actions or update config 
   * })
   */
  extractHardStringsBatch: "i18n-ally.extract-hard-strings-batch",
  /**
   * Detect hard-coded strings in current file (experimental)
   * @value `i18n-ally.detect_hard_strings`
   * @example
   * useCommand(commands.detectHardStrings, async () => {
   *   //do actions or update config 
   * })
   */
  detectHardStrings: "i18n-ally.detect_hard_strings",
  /**
   * %command.open_url%
   * @value `i18n-ally.open-url`
   * @example
   * useCommand(commands.openUrl, async () => {
   *   //do actions or update config 
   * })
   */
  openUrl: "i18n-ally.open-url",
  /**
   * %command.fulfill_keys%
   * @value `i18n-ally.fulfill-keys`
   * @example
   * useCommand(commands.fulfillKeys, async () => {
   *   //do actions or update config 
   * })
   */
  fulfillKeys: "i18n-ally.fulfill-keys",
  /**
   * %command.refresh_usage%
   * @value `i18n-ally.refresh-usage`
   * @example
   * useCommand(commands.refreshUsage, async () => {
   *   //do actions or update config 
   * })
   */
  refreshUsage: "i18n-ally.refresh-usage",
  /**
   * %feedback.support%
   * @value `i18n-ally.support`
   * @example
   * useCommand(commands.support, async () => {
   *   //do actions or update config 
   * })
   */
  support: "i18n-ally.support",
  /**
   * %command.locale_visibility_show%
   * @value `i18n-ally.locale-visibility-show`
   * @example
   * useCommand(commands.localeVisibilityShow, async () => {
   *   //do actions or update config 
   * })
   */
  localeVisibilityShow: "i18n-ally.locale-visibility-show",
  /**
   * %command.locale_visibility_hide%
   * @value `i18n-ally.locale-visibility-hide`
   * @example
   * useCommand(commands.localeVisibilityHide, async () => {
   *   //do actions or update config 
   * })
   */
  localeVisibilityHide: "i18n-ally.locale-visibility-hide",
  /**
   * %command.new_key%
   * @value `i18n-ally.new-key`
   * @example
   * useCommand(commands.newKey, async () => {
   *   //do actions or update config 
   * })
   */
  newKey: "i18n-ally.new-key",
  /**
   * %command.duplicate_key%
   * @value `i18n-ally.duplicate-key`
   * @example
   * useCommand(commands.duplicateKey, async () => {
   *   //do actions or update config 
   * })
   */
  duplicateKey: "i18n-ally.duplicate-key",
  /**
   * %command.mark_key_as_in_use%
   * @value `i18n-ally.mark-key-as-in-use`
   * @example
   * useCommand(commands.markKeyAsInUse, async () => {
   *   //do actions or update config 
   * })
   */
  markKeyAsInUse: "i18n-ally.mark-key-as-in-use",
  /**
   * %command.open_in_editor%
   * @value `i18n-ally.open-in-editor`
   * @example
   * useCommand(commands.openInEditor, async () => {
   *   //do actions or update config 
   * })
   */
  openInEditor: "i18n-ally.open-in-editor",
  /**
   * %command.open_editor%
   * @value `i18n-ally.open-editor`
   * @example
   * useCommand(commands.openEditor, async () => {
   *   //do actions or update config 
   * })
   */
  openEditor: "i18n-ally.open-editor",
  /**
   * %review.leave_comment%
   * @value `i18n-ally.review.comment`
   * @example
   * useCommand(commands.reviewComment, async () => {
   *   //do actions or update config 
   * })
   */
  reviewComment: "i18n-ally.review.comment",
  /**
   * %review.approve%
   * @value `i18n-ally.review.approve`
   * @example
   * useCommand(commands.reviewApprove, async () => {
   *   //do actions or update config 
   * })
   */
  reviewApprove: "i18n-ally.review.approve",
  /**
   * %review.request_change%
   * @value `i18n-ally.review.request-change`
   * @example
   * useCommand(commands.reviewRequestChange, async () => {
   *   //do actions or update config 
   * })
   */
  reviewRequestChange: "i18n-ally.review.request-change",
  /**
   * %review.edit%
   * @value `i18n-ally.review.edit`
   * @example
   * useCommand(commands.reviewEdit, async () => {
   *   //do actions or update config 
   * })
   */
  reviewEdit: "i18n-ally.review.edit",
  /**
   * %review.resolve%
   * @value `i18n-ally.review.resolve`
   * @example
   * useCommand(commands.reviewResolve, async () => {
   *   //do actions or update config 
   * })
   */
  reviewResolve: "i18n-ally.review.resolve",
  /**
   * %review.resolve_all%
   * @value `i18n-ally.review.resolve-thread`
   * @example
   * useCommand(commands.reviewResolveThread, async () => {
   *   //do actions or update config 
   * })
   */
  reviewResolveThread: "i18n-ally.review.resolve-thread",
  /**
   * %review.apply_translation_candidate%
   * @value `i18n-ally.review.apply-translation`
   * @example
   * useCommand(commands.reviewApplyTranslation, async () => {
   *   //do actions or update config 
   * })
   */
  reviewApplyTranslation: "i18n-ally.review.apply-translation",
  /**
   * %review.apply_suggestion%
   * @value `i18n-ally.review.apply-suggestion`
   * @example
   * useCommand(commands.reviewApplySuggestion, async () => {
   *   //do actions or update config 
   * })
   */
  reviewApplySuggestion: "i18n-ally.review.apply-suggestion",
  /**
   * %command.insert_key%
   * @value `i18n-ally.insert-key`
   * @example
   * useCommand(commands.insertKey, async () => {
   *   //do actions or update config 
   * })
   */
  insertKey: "i18n-ally.insert-key",
  /**
   * %command.deepl_usage%
   * @value `i18n-ally.deepl-usage`
   * @example
   * useCommand(commands.deeplUsage, async () => {
   *   //do actions or update config 
   * })
   */
  deeplUsage: "i18n-ally.deepl-usage",
  /**
   * %command.go_to_range%
   * @value `i18n-ally.go-to-range`
   * @example
   * useCommand(commands.goToRange, async () => {
   *   //do actions or update config 
   * })
   */
  goToRange: "i18n-ally.go-to-range",
  /**
   * %command.go_to_next_usage%
   * @value `i18n-ally.go-to-next-usage`
   * @example
   * useCommand(commands.goToNextUsage, async () => {
   *   //do actions or update config 
   * })
   */
  goToNextUsage: "i18n-ally.go-to-next-usage",
  /**
   * %command.go_to_prev_usage%
   * @value `i18n-ally.go-to-prev-usage`
   * @example
   * useCommand(commands.goToPrevUsage, async () => {
   *   //do actions or update config 
   * })
   */
  goToPrevUsage: "i18n-ally.go-to-prev-usage",
  /**
   * %command.show_docs%
   * @value `i18n-ally.open-docs-hard-string`
   * @example
   * useCommand(commands.openDocsHardString, async () => {
   *   //do actions or update config 
   * })
   */
  openDocsHardString: "i18n-ally.open-docs-hard-string",
  /**
   * %command.extract.disable-auto-detect%
   * @value `i18n-ally.extract-disable-auto-detect`
   * @example
   * useCommand(commands.extractDisableAutoDetect, async () => {
   *   //do actions or update config 
   * })
   */
  extractDisableAutoDetect: "i18n-ally.extract-disable-auto-detect",
  /**
   * %command.extract.enable-auto-detect%
   * @value `i18n-ally.extract-enable-auto-detect`
   * @example
   * useCommand(commands.extractEnableAutoDetect, async () => {
   *   //do actions or update config 
   * })
   */
  extractEnableAutoDetect: "i18n-ally.extract-enable-auto-detect",
} satisfies Record<string, CommandKey>

/**
 * Type union of all configs
 */

/**
 * Config keys of `i18n-ally`
 */
export interface I18nAlly {
  /**
   * %config.disabled%
   * @key `i18n-ally.disabled`
   * @default `false`
   * @type `boolean`
   * @example
   *               
   *               
   *               
   */
  "disabled": boolean,
  /**
   * %config.auto_detection%
   * @key `i18n-ally.autoDetection`
   * @default `true`
   * @type `boolean`
   * @example
   *               
   *               
   *               
   */
  "autoDetection": boolean,
  /**
   * %config.encoding%
   * @key `i18n-ally.encoding`
   * @default `"utf-8"`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "encoding": string,
  /**
   * %config.annotations%
   * @key `i18n-ally.annotations`
   * @default `true`
   * @type `boolean`
   * @example
   *               
   *               
   *               
   */
  "annotations": boolean,
  /**
   * %config.annotation_in_place%
   * @key `i18n-ally.annotationInPlace`
   * @default `true`
   * @type `boolean`
   * @example
   *               
   *               
   *               
   */
  "annotationInPlace": boolean,
  /**
   * %config.annotation_max_length%
   * @key `i18n-ally.annotationMaxLength`
   * @default `40`
   * @type `number`
   * @example
   *               
   *               
   *               
   */
  "annotationMaxLength": number,
  /**
   * %config.annotation_delimiter%
   * @key `i18n-ally.annotationDelimiter`
   * @default `"·"`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "annotationDelimiter": string,
  /**
   * %config.include_subfolders%
   * @key `i18n-ally.includeSubfolders`
   * @default `true`
   * @type `boolean`
   * @example
   *               
   *               
   *               
   */
  "includeSubfolders": boolean,
  /**
   * %config.full_reload_on_changed%
   * @key `i18n-ally.fullReloadOnChanged`
   * @default `false`
   * @type `boolean`
   * @example
   *               
   *               
   *               
   */
  "fullReloadOnChanged": boolean,
  /**
   * %config.show_flags%
   * @key `i18n-ally.showFlags`
   * @default `true`
   * @type `boolean`
   * @example
   *               
   *               
   *               
   */
  "showFlags": boolean,
  /**
   * %config.sort_keys%
   * @key `i18n-ally.sortKeys`
   * @default `false`
   * @type `boolean`
   * @example
   *               
   *               
   *               
   */
  "sortKeys": boolean,
  /**
   * %config.sort_compare%
   * @key `i18n-ally.sortCompare`
   * @default `"binary"`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "sortCompare": ("binary" | "locale"),
  /**
   * %config.preferred_delimiter%
   * @key `i18n-ally.preferredDelimiter`
   * @default `"-"`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "preferredDelimiter": string,
  /**
   * %config.readonly%
   * @key `i18n-ally.readonly`
   * @default `false`
   * @type `boolean`
   * @example
   *               
   *               
   *               
   */
  "readonly": boolean,
  /**
   * %config.keep_fulfill%
   * @key `i18n-ally.keepFulfilled`
   * @default `false`
   * @type `boolean`
   * @example
   *               
   *               
   *               
   */
  "keepFulfilled": boolean,
  /**
   * %config.locale_country_map%
   * @key `i18n-ally.localeCountryMap`
   * @default `{}`
   * @type `object`
   * @example
   *               
   *               
   *               
   */
  "localeCountryMap": Record<string, unknown>,
  /**
   * %config.indent%
   * @key `i18n-ally.indent`
   * @default `2`
   * @type `number`
   * @example
   *               
   *               
   *               
   */
  "indent": number,
  /**
   * %config.disable_path_parsing%
   * @key `i18n-ally.disablePathParsing`
   * @default `false`
   * @type `boolean`
   * @example
   *               
   *               
   *               
   */
  "disablePathParsing": boolean,
  /**
   * %config.tab_style%
   * @key `i18n-ally.tabStyle`
   * @default `"space"`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "tabStyle": ("space" | "tab"),
  /**
   * %config.language_tag_system%
   * @key `i18n-ally.languageTagSystem`
   * @default `"bcp47"`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "languageTagSystem": ("bcp47" | "legacy" | "none"),
  /**
   * 
   * @key `i18n-ally.theme.annotation`
   * @default `"rgba(153, 153, 153, .8)"`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "theme.annotation": string,
  /**
   * 
   * @key `i18n-ally.theme.annotationMissing`
   * @default `"rgba(153, 153, 153, .3)"`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "theme.annotationMissing": string,
  /**
   * 
   * @key `i18n-ally.theme.annotationBorder`
   * @default `"rgba(153, 153, 153, .2)"`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "theme.annotationBorder": string,
  /**
   * 
   * @key `i18n-ally.theme.annotationMissingBorder`
   * @default `"rgba(153, 153, 153, .2)"`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "theme.annotationMissingBorder": string,
  /**
   * %config.translate_save_as_candidates%
   * @key `i18n-ally.translate.saveAsCandidates`
   * @default `false`
   * @type `boolean`
   * @example
   *               
   *               
   *               
   */
  "translate.saveAsCandidates": boolean,
  /**
   * %config.translate.fallbackToKey%
   * @key `i18n-ally.translate.fallbackToKey`
   * @default `false`
   * @type `boolean`
   * @example
   *               
   *               
   *               
   */
  "translate.fallbackToKey": boolean,
  /**
   * %config.translate.engines%
   * @key `i18n-ally.translate.engines`
   * @default `["google"]`
   * @type `array`
   * @example
   *               
   *               
   *               
   */
  "translate.engines": ("google" | "google-cn" | "deepl" | "libretranslate" | "baidu" | "openai")[],
  /**
   * %config.translate.parallels%
   * @key `i18n-ally.translate.parallels`
   * @default `5`
   * @type `number`
   * @example
   *               
   *               
   *               
   */
  "translate.parallels": number,
  /**
   * %config.prompt_translating_source%
   * @key `i18n-ally.translate.promptSource`
   * @default `false`
   * @type `boolean`
   * @example
   *               
   *               
   *               
   */
  "translate.promptSource": boolean,
  /**
   * %config.translate_override_existing%
   * @key `i18n-ally.translate.overrideExisting`
   * @default `false`
   * @type `boolean`
   * @example
   *               
   *               
   *               
   */
  "translate.overrideExisting": boolean,
  /**
   * %config.google_api_key%
   * @key `i18n-ally.translate.google.apiKey`
   * @default `null`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "translate.google.apiKey": (string | null),
  /**
   * %config.deepl_api_key%
   * @key `i18n-ally.translate.deepl.apiKey`
   * @default `null`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "translate.deepl.apiKey": (string | null),
  /**
   * %config.baidu_appid%
   * @key `i18n-ally.translate.baidu.appid`
   * @default `null`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "translate.baidu.appid": (string | null),
  /**
   * %config.baidu_app_secret%
   * @key `i18n-ally.translate.baidu.apiSecret`
   * @default `null`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "translate.baidu.apiSecret": (string | null),
  /**
   * %config.deepl_log%
   * @key `i18n-ally.translate.deepl.enableLog`
   * @default `false`
   * @type `boolean`
   * @example
   *               
   *               
   *               
   */
  "translate.deepl.enableLog": boolean,
  /**
   * %config.deepl_use_free_api_entry%
   * @key `i18n-ally.translate.deepl.useFreeApiEntry`
   * @default `false`
   * @type `boolean`
   * @example
   *               
   *               
   *               
   */
  "translate.deepl.useFreeApiEntry": boolean,
  /**
   * %config.libretranslate_api_root%
   * @key `i18n-ally.translate.libre.apiRoot`
   * @default `"http://localhost:5000"`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "translate.libre.apiRoot": string,
  /**
   * %config.openai_api_key%
   * @key `i18n-ally.translate.openai.apiKey`
   * @default `null`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "translate.openai.apiKey": (string | null),
  /**
   * %config.openai_api_root%
   * @key `i18n-ally.translate.openai.apiRoot`
   * @default `"https://api.openai.com"`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "translate.openai.apiRoot": string,
  /**
   * %config.openai_api_model%
   * @key `i18n-ally.translate.openai.apiModel`
   * @default `"gpt-3.5-turbo"`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "translate.openai.apiModel": ("gpt-3.5-turbo" | "gpt-3.5-turbo-16k" | "gpt-3.5-turbo-0301" | "gpt-3.5-turbo-0613" | "gpt-4" | "gpt-4-0314" | "gpt-4-0613" | "gpt-4-32k" | "gpt-4-32k-0314" | "gpt-4-32k-0613"),
  /**
   * %config.derived_keys%
   * @key `i18n-ally.usage.derivedKeyRules`
   * @default `null`
   * @type `array`
   * @example
   *               
   *               
   *               
   */
  "usage.derivedKeyRules": (string[] | null),
  /**
   * 
   * @key `i18n-ally.frameworks.ruby-rails.scopeRoot`
   * @default `"app/views"`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "frameworks.ruby-rails.scopeRoot": string,
  /**
   * 
   * @key `i18n-ally.parsers.typescript.tsNodePath`
   * @default `"node_modules/ts-node/dist/bin.js"`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "parsers.typescript.tsNodePath": string,
  /**
   * 
   * @key `i18n-ally.parsers.typescript.compilerOptions`
   * @default `{}`
   * @type `object`
   * @example
   *               
   *               
   *               
   */
  "parsers.typescript.compilerOptions": Record<string, unknown>,
  /**
   * 
   * @key `i18n-ally.parsers.extendFileExtensions`
   * @default `{}`
   * @type `object`
   * @example
   *               
   *               
   *               
   */
  "parsers.extendFileExtensions": Record<string, unknown>,
  /**
   * %config.review_enabled%
   * @key `i18n-ally.review.enabled`
   * @default `true`
   * @type `boolean`
   * @example
   *               
   *               
   *               
   */
  "review.enabled": boolean,
  /**
   * %config.review_gutters%
   * @key `i18n-ally.review.gutters`
   * @default `true`
   * @type `boolean`
   * @example
   *               
   *               
   *               
   */
  "review.gutters": boolean,
  /**
   * %config.review_remove_on_resolved%
   * @key `i18n-ally.review.removeCommentOnResolved`
   * @default `false`
   * @type `boolean`
   * @example
   *               
   *               
   *               
   */
  "review.removeCommentOnResolved": boolean,
  /**
   * %config.editor_prefer_editor%
   * @key `i18n-ally.editor.preferEditor`
   * @default `false`
   * @type `boolean`
   * @example
   *               
   *               
   *               
   */
  "editor.preferEditor": boolean,
  /**
   * %config.keygen_strategy%
   * @key `i18n-ally.extract.keygenStrategy`
   * @default `"slug"`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "extract.keygenStrategy": ("slug" | "random" | "empty" | "source"),
  /**
   * %config.keygen_style%
   * @key `i18n-ally.extract.keygenStyle`
   * @default `"default"`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "extract.keygenStyle": ("default" | "kebab-case" | "snake_case" | "camelCase" | "PascalCase" | "ALL_CAPS"),
  /**
   * %config.key_prefix%
   * @key `i18n-ally.extract.keyPrefix`
   * @default `""`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "extract.keyPrefix": string,
  /**
   * %config.key_max_length%
   * @key `i18n-ally.extract.keyMaxLength`
   * @default `null`
   * @type `number`
   * @example
   *               
   *               
   *               
   */
  "extract.keyMaxLength": (number | null),
  /**
   * %config.target_picking_strategy%
   * @key `i18n-ally.extract.targetPickingStrategy`
   * @default `"none"`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "extract.targetPickingStrategy": ("none" | "most-similar" | "most-similar-by-key" | "file-previous" | "global-previous"),
  /**
   * Parser options for extracting HTML, see https://github.com/lokalise/i18n-ally/blob/master/src/extraction/parsers/options.ts
   * @key `i18n-ally.extract.parsers.html`
   * @default `{}`
   * @type `object`
   * @example
   *               
   *               
   *               
   */
  "extract.parsers.html": Record<string, unknown>,
  /**
   * Parser options for extracting JS/TS/JSX/TSX, see https://github.com/lokalise/i18n-ally/blob/master/src/extraction/parsers/options.ts
   * @key `i18n-ally.extract.parsers.babel`
   * @default `{}`
   * @type `object`
   * @example
   *               
   *               
   *               
   */
  "extract.parsers.babel": Record<string, unknown>,
  /**
   * Enables hard-coded strings detection automatically whenever opening a supported file
   * @key `i18n-ally.extract.autoDetect`
   * @default `false`
   * @type `boolean`
   * @example
   *               
   *               
   *               
   */
  "extract.autoDetect": boolean,
  /**
   * Strings to be ignored on hard-coded strings detection, by files
   * @key `i18n-ally.extract.ignoredByFiles`
   * @default `{}`
   * @type `object`
   * @example
   *               
   *               
   *               
   */
  "extract.ignoredByFiles": Record<string, unknown>,
}

/**
 * Scoped defaults of `i18n-ally`
 */
const _i18nAlly = {
/**
 * scope: `i18n-ally`
 */
  scope: "i18n-ally",
/**
 * Keys' defaults of `i18n-ally`
 */
  defaults: {
    "disabled": false,
    "autoDetection": true,
    "encoding": "utf-8",
    "annotations": true,
    "annotationInPlace": true,
    "annotationMaxLength": 40,
    "annotationDelimiter": "·",
    "includeSubfolders": true,
    "fullReloadOnChanged": false,
    "showFlags": true,
    "sortKeys": false,
    "sortCompare": "binary",
    "preferredDelimiter": "-",
    "readonly": false,
    "keepFulfilled": false,
    "localeCountryMap": {},
    "indent": 2,
    "disablePathParsing": false,
    "tabStyle": "space",
    "languageTagSystem": "bcp47",
    "theme.annotation": "rgba(153, 153, 153, .8)",
    "theme.annotationMissing": "rgba(153, 153, 153, .3)",
    "theme.annotationBorder": "rgba(153, 153, 153, .2)",
    "theme.annotationMissingBorder": "rgba(153, 153, 153, .2)",
    "translate.saveAsCandidates": false,
    "translate.fallbackToKey": false,
    "translate.engines": ["google"],
    "translate.parallels": 5,
    "translate.promptSource": false,
    "translate.overrideExisting": false,
    "translate.google.apiKey": null,
    "translate.deepl.apiKey": null,
    "translate.baidu.appid": null,
    "translate.baidu.apiSecret": null,
    "translate.deepl.enableLog": false,
    "translate.deepl.useFreeApiEntry": false,
    "translate.libre.apiRoot": "http://localhost:5000",
    "translate.openai.apiKey": null,
    "translate.openai.apiRoot": "https://api.openai.com",
    "translate.openai.apiModel": "gpt-3.5-turbo",
    "usage.derivedKeyRules": null,
    "frameworks.ruby-rails.scopeRoot": "app/views",
    "parsers.typescript.tsNodePath": "node_modules/ts-node/dist/bin.js",
    "parsers.typescript.compilerOptions": {},
    "parsers.extendFileExtensions": {},
    "review.enabled": true,
    "review.gutters": true,
    "review.removeCommentOnResolved": false,
    "editor.preferEditor": false,
    "extract.keygenStrategy": "slug",
    "extract.keygenStyle": "default",
    "extract.keyPrefix": "",
    "extract.keyMaxLength": null,
    "extract.targetPickingStrategy": "none",
    "extract.parsers.html": {},
    "extract.parsers.babel": {},
    "extract.autoDetect": false,
    "extract.ignoredByFiles": {},
  } satisfies I18nAlly,
}

/**
 * Reactive ConfigObject of `i18n-ally`
 * @example
 * //import { i18nAllyConfigObject } from '@/meta' //import on top        
 * 
 *         
 */
export const i18nAllyConfigObject = defineConfigObject<I18nAlly>(
  _i18nAlly.scope,
  _i18nAlly.defaults
)


/**
 * Reactive ToConfigRefs of `i18n-ally`
 */
export const i18nAllyConfigs = defineConfigs<I18nAlly>(
  _i18nAlly.scope,
  _i18nAlly.defaults
)


/**
 * Config keys of `i18n-ally.theme`
 */
export interface Theme {
  /**
   * 
   * @key `i18n-ally.theme.annotation`
   * @default `"rgba(153, 153, 153, .8)"`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "annotation": string,
  /**
   * 
   * @key `i18n-ally.theme.annotationMissing`
   * @default `"rgba(153, 153, 153, .3)"`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "annotationMissing": string,
  /**
   * 
   * @key `i18n-ally.theme.annotationBorder`
   * @default `"rgba(153, 153, 153, .2)"`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "annotationBorder": string,
  /**
   * 
   * @key `i18n-ally.theme.annotationMissingBorder`
   * @default `"rgba(153, 153, 153, .2)"`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "annotationMissingBorder": string,
}

/**
 * Scoped defaults of `i18n-ally.theme`
 */
const _theme = {
/**
 * scope: `i18n-ally.theme`
 */
  scope: "i18n-ally.theme",
/**
 * Keys' defaults of `i18n-ally.theme`
 */
  defaults: {
    "annotation": "rgba(153, 153, 153, .8)",
    "annotationMissing": "rgba(153, 153, 153, .3)",
    "annotationBorder": "rgba(153, 153, 153, .2)",
    "annotationMissingBorder": "rgba(153, 153, 153, .2)",
  } satisfies Theme,
}

/**
 * Reactive ConfigObject of `i18n-ally.theme`
 * @example
 * //import { themeConfigObject } from '@/meta' //import on top        
 * 
 *         
 */
export const themeConfigObject = defineConfigObject<Theme>(
  _theme.scope,
  _theme.defaults
)


/**
 * Reactive ToConfigRefs of `i18n-ally.theme`
 */
export const themeConfigs = defineConfigs<Theme>(
  _theme.scope,
  _theme.defaults
)


/**
 * Config keys of `i18n-ally.regex`
 */
export interface Regex {
}

/**
 * Scoped defaults of `i18n-ally.regex`
 */
const _regex = {
/**
 * scope: `i18n-ally.regex`
 */
  scope: "i18n-ally.regex",
/**
 * Keys' defaults of `i18n-ally.regex`
 */
  defaults: {
  } satisfies Regex,
}

/**
 * Reactive ConfigObject of `i18n-ally.regex`
 * @example
 * //import { regexConfigObject } from '@/meta' //import on top        
 * 
 *         
 */
export const regexConfigObject = defineConfigObject<Regex>(
  _regex.scope,
  _regex.defaults
)


/**
 * Reactive ToConfigRefs of `i18n-ally.regex`
 */
export const regexConfigs = defineConfigs<Regex>(
  _regex.scope,
  _regex.defaults
)


/**
 * Config keys of `i18n-ally.refactor`
 */
export interface Refactor {
}

/**
 * Scoped defaults of `i18n-ally.refactor`
 */
const _refactor = {
/**
 * scope: `i18n-ally.refactor`
 */
  scope: "i18n-ally.refactor",
/**
 * Keys' defaults of `i18n-ally.refactor`
 */
  defaults: {
  } satisfies Refactor,
}

/**
 * Reactive ConfigObject of `i18n-ally.refactor`
 * @example
 * //import { refactorConfigObject } from '@/meta' //import on top        
 * 
 *         
 */
export const refactorConfigObject = defineConfigObject<Refactor>(
  _refactor.scope,
  _refactor.defaults
)


/**
 * Reactive ToConfigRefs of `i18n-ally.refactor`
 */
export const refactorConfigs = defineConfigs<Refactor>(
  _refactor.scope,
  _refactor.defaults
)


/**
 * Config keys of `i18n-ally.translate`
 */
export interface Translate {
  /**
   * %config.translate_save_as_candidates%
   * @key `i18n-ally.translate.saveAsCandidates`
   * @default `false`
   * @type `boolean`
   * @example
   *               
   *               
   *               
   */
  "saveAsCandidates": boolean,
  /**
   * %config.translate.fallbackToKey%
   * @key `i18n-ally.translate.fallbackToKey`
   * @default `false`
   * @type `boolean`
   * @example
   *               
   *               
   *               
   */
  "fallbackToKey": boolean,
  /**
   * %config.translate.engines%
   * @key `i18n-ally.translate.engines`
   * @default `["google"]`
   * @type `array`
   * @example
   *               
   *               
   *               
   */
  "engines": ("google" | "google-cn" | "deepl" | "libretranslate" | "baidu" | "openai")[],
  /**
   * %config.translate.parallels%
   * @key `i18n-ally.translate.parallels`
   * @default `5`
   * @type `number`
   * @example
   *               
   *               
   *               
   */
  "parallels": number,
  /**
   * %config.prompt_translating_source%
   * @key `i18n-ally.translate.promptSource`
   * @default `false`
   * @type `boolean`
   * @example
   *               
   *               
   *               
   */
  "promptSource": boolean,
  /**
   * %config.translate_override_existing%
   * @key `i18n-ally.translate.overrideExisting`
   * @default `false`
   * @type `boolean`
   * @example
   *               
   *               
   *               
   */
  "overrideExisting": boolean,
  /**
   * %config.google_api_key%
   * @key `i18n-ally.translate.google.apiKey`
   * @default `null`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "google.apiKey": (string | null),
  /**
   * %config.deepl_api_key%
   * @key `i18n-ally.translate.deepl.apiKey`
   * @default `null`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "deepl.apiKey": (string | null),
  /**
   * %config.baidu_appid%
   * @key `i18n-ally.translate.baidu.appid`
   * @default `null`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "baidu.appid": (string | null),
  /**
   * %config.baidu_app_secret%
   * @key `i18n-ally.translate.baidu.apiSecret`
   * @default `null`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "baidu.apiSecret": (string | null),
  /**
   * %config.deepl_log%
   * @key `i18n-ally.translate.deepl.enableLog`
   * @default `false`
   * @type `boolean`
   * @example
   *               
   *               
   *               
   */
  "deepl.enableLog": boolean,
  /**
   * %config.deepl_use_free_api_entry%
   * @key `i18n-ally.translate.deepl.useFreeApiEntry`
   * @default `false`
   * @type `boolean`
   * @example
   *               
   *               
   *               
   */
  "deepl.useFreeApiEntry": boolean,
  /**
   * %config.libretranslate_api_root%
   * @key `i18n-ally.translate.libre.apiRoot`
   * @default `"http://localhost:5000"`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "libre.apiRoot": string,
  /**
   * %config.openai_api_key%
   * @key `i18n-ally.translate.openai.apiKey`
   * @default `null`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "openai.apiKey": (string | null),
  /**
   * %config.openai_api_root%
   * @key `i18n-ally.translate.openai.apiRoot`
   * @default `"https://api.openai.com"`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "openai.apiRoot": string,
  /**
   * %config.openai_api_model%
   * @key `i18n-ally.translate.openai.apiModel`
   * @default `"gpt-3.5-turbo"`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "openai.apiModel": ("gpt-3.5-turbo" | "gpt-3.5-turbo-16k" | "gpt-3.5-turbo-0301" | "gpt-3.5-turbo-0613" | "gpt-4" | "gpt-4-0314" | "gpt-4-0613" | "gpt-4-32k" | "gpt-4-32k-0314" | "gpt-4-32k-0613"),
}

/**
 * Scoped defaults of `i18n-ally.translate`
 */
const _translate = {
/**
 * scope: `i18n-ally.translate`
 */
  scope: "i18n-ally.translate",
/**
 * Keys' defaults of `i18n-ally.translate`
 */
  defaults: {
    "saveAsCandidates": false,
    "fallbackToKey": false,
    "engines": ["google"],
    "parallels": 5,
    "promptSource": false,
    "overrideExisting": false,
    "google.apiKey": null,
    "deepl.apiKey": null,
    "baidu.appid": null,
    "baidu.apiSecret": null,
    "deepl.enableLog": false,
    "deepl.useFreeApiEntry": false,
    "libre.apiRoot": "http://localhost:5000",
    "openai.apiKey": null,
    "openai.apiRoot": "https://api.openai.com",
    "openai.apiModel": "gpt-3.5-turbo",
  } satisfies Translate,
}

/**
 * Reactive ConfigObject of `i18n-ally.translate`
 * @example
 * //import { translateConfigObject } from '@/meta' //import on top        
 * 
 *         
 */
export const translateConfigObject = defineConfigObject<Translate>(
  _translate.scope,
  _translate.defaults
)


/**
 * Reactive ToConfigRefs of `i18n-ally.translate`
 */
export const translateConfigs = defineConfigs<Translate>(
  _translate.scope,
  _translate.defaults
)


/**
 * Config keys of `i18n-ally.translate.google`
 */
export interface TranslateGoogle {
  /**
   * %config.google_api_key%
   * @key `i18n-ally.translate.google.apiKey`
   * @default `null`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "apiKey": (string | null),
}

/**
 * Scoped defaults of `i18n-ally.translate.google`
 */
const _translateGoogle = {
/**
 * scope: `i18n-ally.translate.google`
 */
  scope: "i18n-ally.translate.google",
/**
 * Keys' defaults of `i18n-ally.translate.google`
 */
  defaults: {
    "apiKey": null,
  } satisfies TranslateGoogle,
}

/**
 * Reactive ConfigObject of `i18n-ally.translate.google`
 * @example
 * //import { translateGoogleConfigObject } from '@/meta' //import on top        
 * 
 *         
 */
export const translateGoogleConfigObject = defineConfigObject<TranslateGoogle>(
  _translateGoogle.scope,
  _translateGoogle.defaults
)


/**
 * Reactive ToConfigRefs of `i18n-ally.translate.google`
 */
export const translateGoogleConfigs = defineConfigs<TranslateGoogle>(
  _translateGoogle.scope,
  _translateGoogle.defaults
)


/**
 * Config keys of `i18n-ally.translate.deepl`
 */
export interface TranslateDeepl {
  /**
   * %config.deepl_api_key%
   * @key `i18n-ally.translate.deepl.apiKey`
   * @default `null`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "apiKey": (string | null),
  /**
   * %config.deepl_log%
   * @key `i18n-ally.translate.deepl.enableLog`
   * @default `false`
   * @type `boolean`
   * @example
   *               
   *               
   *               
   */
  "enableLog": boolean,
  /**
   * %config.deepl_use_free_api_entry%
   * @key `i18n-ally.translate.deepl.useFreeApiEntry`
   * @default `false`
   * @type `boolean`
   * @example
   *               
   *               
   *               
   */
  "useFreeApiEntry": boolean,
}

/**
 * Scoped defaults of `i18n-ally.translate.deepl`
 */
const _translateDeepl = {
/**
 * scope: `i18n-ally.translate.deepl`
 */
  scope: "i18n-ally.translate.deepl",
/**
 * Keys' defaults of `i18n-ally.translate.deepl`
 */
  defaults: {
    "apiKey": null,
    "enableLog": false,
    "useFreeApiEntry": false,
  } satisfies TranslateDeepl,
}

/**
 * Reactive ConfigObject of `i18n-ally.translate.deepl`
 * @example
 * //import { translateDeeplConfigObject } from '@/meta' //import on top        
 * 
 *         
 */
export const translateDeeplConfigObject = defineConfigObject<TranslateDeepl>(
  _translateDeepl.scope,
  _translateDeepl.defaults
)


/**
 * Reactive ToConfigRefs of `i18n-ally.translate.deepl`
 */
export const translateDeeplConfigs = defineConfigs<TranslateDeepl>(
  _translateDeepl.scope,
  _translateDeepl.defaults
)


/**
 * Config keys of `i18n-ally.translate.baidu`
 */
export interface TranslateBaidu {
  /**
   * %config.baidu_appid%
   * @key `i18n-ally.translate.baidu.appid`
   * @default `null`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "appid": (string | null),
  /**
   * %config.baidu_app_secret%
   * @key `i18n-ally.translate.baidu.apiSecret`
   * @default `null`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "apiSecret": (string | null),
}

/**
 * Scoped defaults of `i18n-ally.translate.baidu`
 */
const _translateBaidu = {
/**
 * scope: `i18n-ally.translate.baidu`
 */
  scope: "i18n-ally.translate.baidu",
/**
 * Keys' defaults of `i18n-ally.translate.baidu`
 */
  defaults: {
    "appid": null,
    "apiSecret": null,
  } satisfies TranslateBaidu,
}

/**
 * Reactive ConfigObject of `i18n-ally.translate.baidu`
 * @example
 * //import { translateBaiduConfigObject } from '@/meta' //import on top        
 * 
 *         
 */
export const translateBaiduConfigObject = defineConfigObject<TranslateBaidu>(
  _translateBaidu.scope,
  _translateBaidu.defaults
)


/**
 * Reactive ToConfigRefs of `i18n-ally.translate.baidu`
 */
export const translateBaiduConfigs = defineConfigs<TranslateBaidu>(
  _translateBaidu.scope,
  _translateBaidu.defaults
)


/**
 * Config keys of `i18n-ally.translate.libre`
 */
export interface TranslateLibre {
  /**
   * %config.libretranslate_api_root%
   * @key `i18n-ally.translate.libre.apiRoot`
   * @default `"http://localhost:5000"`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "apiRoot": string,
}

/**
 * Scoped defaults of `i18n-ally.translate.libre`
 */
const _translateLibre = {
/**
 * scope: `i18n-ally.translate.libre`
 */
  scope: "i18n-ally.translate.libre",
/**
 * Keys' defaults of `i18n-ally.translate.libre`
 */
  defaults: {
    "apiRoot": "http://localhost:5000",
  } satisfies TranslateLibre,
}

/**
 * Reactive ConfigObject of `i18n-ally.translate.libre`
 * @example
 * //import { translateLibreConfigObject } from '@/meta' //import on top        
 * 
 *         
 */
export const translateLibreConfigObject = defineConfigObject<TranslateLibre>(
  _translateLibre.scope,
  _translateLibre.defaults
)


/**
 * Reactive ToConfigRefs of `i18n-ally.translate.libre`
 */
export const translateLibreConfigs = defineConfigs<TranslateLibre>(
  _translateLibre.scope,
  _translateLibre.defaults
)


/**
 * Config keys of `i18n-ally.translate.openai`
 */
export interface TranslateOpenai {
  /**
   * %config.openai_api_key%
   * @key `i18n-ally.translate.openai.apiKey`
   * @default `null`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "apiKey": (string | null),
  /**
   * %config.openai_api_root%
   * @key `i18n-ally.translate.openai.apiRoot`
   * @default `"https://api.openai.com"`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "apiRoot": string,
  /**
   * %config.openai_api_model%
   * @key `i18n-ally.translate.openai.apiModel`
   * @default `"gpt-3.5-turbo"`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "apiModel": ("gpt-3.5-turbo" | "gpt-3.5-turbo-16k" | "gpt-3.5-turbo-0301" | "gpt-3.5-turbo-0613" | "gpt-4" | "gpt-4-0314" | "gpt-4-0613" | "gpt-4-32k" | "gpt-4-32k-0314" | "gpt-4-32k-0613"),
}

/**
 * Scoped defaults of `i18n-ally.translate.openai`
 */
const _translateOpenai = {
/**
 * scope: `i18n-ally.translate.openai`
 */
  scope: "i18n-ally.translate.openai",
/**
 * Keys' defaults of `i18n-ally.translate.openai`
 */
  defaults: {
    "apiKey": null,
    "apiRoot": "https://api.openai.com",
    "apiModel": "gpt-3.5-turbo",
  } satisfies TranslateOpenai,
}

/**
 * Reactive ConfigObject of `i18n-ally.translate.openai`
 * @example
 * //import { translateOpenaiConfigObject } from '@/meta' //import on top        
 * 
 *         
 */
export const translateOpenaiConfigObject = defineConfigObject<TranslateOpenai>(
  _translateOpenai.scope,
  _translateOpenai.defaults
)


/**
 * Reactive ToConfigRefs of `i18n-ally.translate.openai`
 */
export const translateOpenaiConfigs = defineConfigs<TranslateOpenai>(
  _translateOpenai.scope,
  _translateOpenai.defaults
)


/**
 * Config keys of `i18n-ally.usage`
 */
export interface Usage {
  /**
   * %config.derived_keys%
   * @key `i18n-ally.usage.derivedKeyRules`
   * @default `null`
   * @type `array`
   * @example
   *               
   *               
   *               
   */
  "derivedKeyRules": (string[] | null),
}

/**
 * Scoped defaults of `i18n-ally.usage`
 */
const _usage = {
/**
 * scope: `i18n-ally.usage`
 */
  scope: "i18n-ally.usage",
/**
 * Keys' defaults of `i18n-ally.usage`
 */
  defaults: {
    "derivedKeyRules": null,
  } satisfies Usage,
}

/**
 * Reactive ConfigObject of `i18n-ally.usage`
 * @example
 * //import { usageConfigObject } from '@/meta' //import on top        
 * 
 *         
 */
export const usageConfigObject = defineConfigObject<Usage>(
  _usage.scope,
  _usage.defaults
)


/**
 * Reactive ToConfigRefs of `i18n-ally.usage`
 */
export const usageConfigs = defineConfigs<Usage>(
  _usage.scope,
  _usage.defaults
)


/**
 * Config keys of `i18n-ally.frameworks`
 */
export interface Frameworks {
  /**
   * 
   * @key `i18n-ally.frameworks.ruby-rails.scopeRoot`
   * @default `"app/views"`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "ruby-rails.scopeRoot": string,
}

/**
 * Scoped defaults of `i18n-ally.frameworks`
 */
const _frameworks = {
/**
 * scope: `i18n-ally.frameworks`
 */
  scope: "i18n-ally.frameworks",
/**
 * Keys' defaults of `i18n-ally.frameworks`
 */
  defaults: {
    "ruby-rails.scopeRoot": "app/views",
  } satisfies Frameworks,
}

/**
 * Reactive ConfigObject of `i18n-ally.frameworks`
 * @example
 * //import { frameworksConfigObject } from '@/meta' //import on top        
 * 
 *         
 */
export const frameworksConfigObject = defineConfigObject<Frameworks>(
  _frameworks.scope,
  _frameworks.defaults
)


/**
 * Reactive ToConfigRefs of `i18n-ally.frameworks`
 */
export const frameworksConfigs = defineConfigs<Frameworks>(
  _frameworks.scope,
  _frameworks.defaults
)


/**
 * Config keys of `i18n-ally.frameworks.ruby-rails`
 */
export interface FrameworksRubyRails {
  /**
   * 
   * @key `i18n-ally.frameworks.ruby-rails.scopeRoot`
   * @default `"app/views"`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "scopeRoot": string,
}

/**
 * Scoped defaults of `i18n-ally.frameworks.ruby-rails`
 */
const _frameworksRubyRails = {
/**
 * scope: `i18n-ally.frameworks.ruby-rails`
 */
  scope: "i18n-ally.frameworks.ruby-rails",
/**
 * Keys' defaults of `i18n-ally.frameworks.ruby-rails`
 */
  defaults: {
    "scopeRoot": "app/views",
  } satisfies FrameworksRubyRails,
}

/**
 * Reactive ConfigObject of `i18n-ally.frameworks.ruby-rails`
 * @example
 * //import { frameworksRubyRailsConfigObject } from '@/meta' //import on top        
 * 
 *         
 */
export const frameworksRubyRailsConfigObject = defineConfigObject<FrameworksRubyRails>(
  _frameworksRubyRails.scope,
  _frameworksRubyRails.defaults
)


/**
 * Reactive ToConfigRefs of `i18n-ally.frameworks.ruby-rails`
 */
export const frameworksRubyRailsConfigs = defineConfigs<FrameworksRubyRails>(
  _frameworksRubyRails.scope,
  _frameworksRubyRails.defaults
)


/**
 * Config keys of `i18n-ally.parsers`
 */
export interface Parsers {
  /**
   * 
   * @key `i18n-ally.parsers.typescript.tsNodePath`
   * @default `"node_modules/ts-node/dist/bin.js"`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "typescript.tsNodePath": string,
  /**
   * 
   * @key `i18n-ally.parsers.typescript.compilerOptions`
   * @default `{}`
   * @type `object`
   * @example
   *               
   *               
   *               
   */
  "typescript.compilerOptions": Record<string, unknown>,
  /**
   * 
   * @key `i18n-ally.parsers.extendFileExtensions`
   * @default `{}`
   * @type `object`
   * @example
   *               
   *               
   *               
   */
  "extendFileExtensions": Record<string, unknown>,
}

/**
 * Scoped defaults of `i18n-ally.parsers`
 */
const _parsers = {
/**
 * scope: `i18n-ally.parsers`
 */
  scope: "i18n-ally.parsers",
/**
 * Keys' defaults of `i18n-ally.parsers`
 */
  defaults: {
    "typescript.tsNodePath": "node_modules/ts-node/dist/bin.js",
    "typescript.compilerOptions": {},
    "extendFileExtensions": {},
  } satisfies Parsers,
}

/**
 * Reactive ConfigObject of `i18n-ally.parsers`
 * @example
 * //import { parsersConfigObject } from '@/meta' //import on top        
 * 
 *         
 */
export const parsersConfigObject = defineConfigObject<Parsers>(
  _parsers.scope,
  _parsers.defaults
)


/**
 * Reactive ToConfigRefs of `i18n-ally.parsers`
 */
export const parsersConfigs = defineConfigs<Parsers>(
  _parsers.scope,
  _parsers.defaults
)


/**
 * Config keys of `i18n-ally.parsers.typescript`
 */
export interface ParsersTypescript {
  /**
   * 
   * @key `i18n-ally.parsers.typescript.tsNodePath`
   * @default `"node_modules/ts-node/dist/bin.js"`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "tsNodePath": string,
  /**
   * 
   * @key `i18n-ally.parsers.typescript.compilerOptions`
   * @default `{}`
   * @type `object`
   * @example
   *               
   *               
   *               
   */
  "compilerOptions": Record<string, unknown>,
}

/**
 * Scoped defaults of `i18n-ally.parsers.typescript`
 */
const _parsersTypescript = {
/**
 * scope: `i18n-ally.parsers.typescript`
 */
  scope: "i18n-ally.parsers.typescript",
/**
 * Keys' defaults of `i18n-ally.parsers.typescript`
 */
  defaults: {
    "tsNodePath": "node_modules/ts-node/dist/bin.js",
    "compilerOptions": {},
  } satisfies ParsersTypescript,
}

/**
 * Reactive ConfigObject of `i18n-ally.parsers.typescript`
 * @example
 * //import { parsersTypescriptConfigObject } from '@/meta' //import on top        
 * 
 *         
 */
export const parsersTypescriptConfigObject = defineConfigObject<ParsersTypescript>(
  _parsersTypescript.scope,
  _parsersTypescript.defaults
)


/**
 * Reactive ToConfigRefs of `i18n-ally.parsers.typescript`
 */
export const parsersTypescriptConfigs = defineConfigs<ParsersTypescript>(
  _parsersTypescript.scope,
  _parsersTypescript.defaults
)


/**
 * Config keys of `i18n-ally.review`
 */
export interface Review {
  /**
   * %config.review_enabled%
   * @key `i18n-ally.review.enabled`
   * @default `true`
   * @type `boolean`
   * @example
   *               
   *               
   *               
   */
  "enabled": boolean,
  /**
   * %config.review_gutters%
   * @key `i18n-ally.review.gutters`
   * @default `true`
   * @type `boolean`
   * @example
   *               
   *               
   *               
   */
  "gutters": boolean,
  /**
   * %config.review_remove_on_resolved%
   * @key `i18n-ally.review.removeCommentOnResolved`
   * @default `false`
   * @type `boolean`
   * @example
   *               
   *               
   *               
   */
  "removeCommentOnResolved": boolean,
}

/**
 * Scoped defaults of `i18n-ally.review`
 */
const _review = {
/**
 * scope: `i18n-ally.review`
 */
  scope: "i18n-ally.review",
/**
 * Keys' defaults of `i18n-ally.review`
 */
  defaults: {
    "enabled": true,
    "gutters": true,
    "removeCommentOnResolved": false,
  } satisfies Review,
}

/**
 * Reactive ConfigObject of `i18n-ally.review`
 * @example
 * //import { reviewConfigObject } from '@/meta' //import on top        
 * 
 *         
 */
export const reviewConfigObject = defineConfigObject<Review>(
  _review.scope,
  _review.defaults
)


/**
 * Reactive ToConfigRefs of `i18n-ally.review`
 */
export const reviewConfigs = defineConfigs<Review>(
  _review.scope,
  _review.defaults
)


/**
 * Config keys of `i18n-ally.review.user`
 */
export interface ReviewUser {
}

/**
 * Scoped defaults of `i18n-ally.review.user`
 */
const _reviewUser = {
/**
 * scope: `i18n-ally.review.user`
 */
  scope: "i18n-ally.review.user",
/**
 * Keys' defaults of `i18n-ally.review.user`
 */
  defaults: {
  } satisfies ReviewUser,
}

/**
 * Reactive ConfigObject of `i18n-ally.review.user`
 * @example
 * //import { reviewUserConfigObject } from '@/meta' //import on top        
 * 
 *         
 */
export const reviewUserConfigObject = defineConfigObject<ReviewUser>(
  _reviewUser.scope,
  _reviewUser.defaults
)


/**
 * Reactive ToConfigRefs of `i18n-ally.review.user`
 */
export const reviewUserConfigs = defineConfigs<ReviewUser>(
  _reviewUser.scope,
  _reviewUser.defaults
)


/**
 * Config keys of `i18n-ally.editor`
 */
export interface Editor {
  /**
   * %config.editor_prefer_editor%
   * @key `i18n-ally.editor.preferEditor`
   * @default `false`
   * @type `boolean`
   * @example
   *               
   *               
   *               
   */
  "preferEditor": boolean,
}

/**
 * Scoped defaults of `i18n-ally.editor`
 */
const _editor = {
/**
 * scope: `i18n-ally.editor`
 */
  scope: "i18n-ally.editor",
/**
 * Keys' defaults of `i18n-ally.editor`
 */
  defaults: {
    "preferEditor": false,
  } satisfies Editor,
}

/**
 * Reactive ConfigObject of `i18n-ally.editor`
 * @example
 * //import { editorConfigObject } from '@/meta' //import on top        
 * 
 *         
 */
export const editorConfigObject = defineConfigObject<Editor>(
  _editor.scope,
  _editor.defaults
)


/**
 * Reactive ToConfigRefs of `i18n-ally.editor`
 */
export const editorConfigs = defineConfigs<Editor>(
  _editor.scope,
  _editor.defaults
)


/**
 * Config keys of `i18n-ally.extract`
 */
export interface Extract {
  /**
   * %config.keygen_strategy%
   * @key `i18n-ally.extract.keygenStrategy`
   * @default `"slug"`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "keygenStrategy": ("slug" | "random" | "empty" | "source"),
  /**
   * %config.keygen_style%
   * @key `i18n-ally.extract.keygenStyle`
   * @default `"default"`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "keygenStyle": ("default" | "kebab-case" | "snake_case" | "camelCase" | "PascalCase" | "ALL_CAPS"),
  /**
   * %config.key_prefix%
   * @key `i18n-ally.extract.keyPrefix`
   * @default `""`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "keyPrefix": string,
  /**
   * %config.key_max_length%
   * @key `i18n-ally.extract.keyMaxLength`
   * @default `null`
   * @type `number`
   * @example
   *               
   *               
   *               
   */
  "keyMaxLength": (number | null),
  /**
   * %config.target_picking_strategy%
   * @key `i18n-ally.extract.targetPickingStrategy`
   * @default `"none"`
   * @type `string`
   * @example
   *               
   *               
   *               
   */
  "targetPickingStrategy": ("none" | "most-similar" | "most-similar-by-key" | "file-previous" | "global-previous"),
  /**
   * Parser options for extracting HTML, see https://github.com/lokalise/i18n-ally/blob/master/src/extraction/parsers/options.ts
   * @key `i18n-ally.extract.parsers.html`
   * @default `{}`
   * @type `object`
   * @example
   *               
   *               
   *               
   */
  "parsers.html": Record<string, unknown>,
  /**
   * Parser options for extracting JS/TS/JSX/TSX, see https://github.com/lokalise/i18n-ally/blob/master/src/extraction/parsers/options.ts
   * @key `i18n-ally.extract.parsers.babel`
   * @default `{}`
   * @type `object`
   * @example
   *               
   *               
   *               
   */
  "parsers.babel": Record<string, unknown>,
  /**
   * Enables hard-coded strings detection automatically whenever opening a supported file
   * @key `i18n-ally.extract.autoDetect`
   * @default `false`
   * @type `boolean`
   * @example
   *               
   *               
   *               
   */
  "autoDetect": boolean,
  /**
   * Strings to be ignored on hard-coded strings detection, by files
   * @key `i18n-ally.extract.ignoredByFiles`
   * @default `{}`
   * @type `object`
   * @example
   *               
   *               
   *               
   */
  "ignoredByFiles": Record<string, unknown>,
}

/**
 * Scoped defaults of `i18n-ally.extract`
 */
const _extract = {
/**
 * scope: `i18n-ally.extract`
 */
  scope: "i18n-ally.extract",
/**
 * Keys' defaults of `i18n-ally.extract`
 */
  defaults: {
    "keygenStrategy": "slug",
    "keygenStyle": "default",
    "keyPrefix": "",
    "keyMaxLength": null,
    "targetPickingStrategy": "none",
    "parsers.html": {},
    "parsers.babel": {},
    "autoDetect": false,
    "ignoredByFiles": {},
  } satisfies Extract,
}

/**
 * Reactive ConfigObject of `i18n-ally.extract`
 * @example
 * //import { extractConfigObject } from '@/meta' //import on top        
 * 
 *         
 */
export const extractConfigObject = defineConfigObject<Extract>(
  _extract.scope,
  _extract.defaults
)


/**
 * Reactive ToConfigRefs of `i18n-ally.extract`
 */
export const extractConfigs = defineConfigs<Extract>(
  _extract.scope,
  _extract.defaults
)


/**
 * Config keys of `i18n-ally.extract.parsers`
 */
export interface ExtractParsers {
  /**
   * Parser options for extracting HTML, see https://github.com/lokalise/i18n-ally/blob/master/src/extraction/parsers/options.ts
   * @key `i18n-ally.extract.parsers.html`
   * @default `{}`
   * @type `object`
   * @example
   *               
   *               
   *               
   */
  "html": Record<string, unknown>,
  /**
   * Parser options for extracting JS/TS/JSX/TSX, see https://github.com/lokalise/i18n-ally/blob/master/src/extraction/parsers/options.ts
   * @key `i18n-ally.extract.parsers.babel`
   * @default `{}`
   * @type `object`
   * @example
   *               
   *               
   *               
   */
  "babel": Record<string, unknown>,
}

/**
 * Scoped defaults of `i18n-ally.extract.parsers`
 */
const _extractParsers = {
/**
 * scope: `i18n-ally.extract.parsers`
 */
  scope: "i18n-ally.extract.parsers",
/**
 * Keys' defaults of `i18n-ally.extract.parsers`
 */
  defaults: {
    "html": {},
    "babel": {},
  } satisfies ExtractParsers,
}

/**
 * Reactive ConfigObject of `i18n-ally.extract.parsers`
 * @example
 * //import { extractParsersConfigObject } from '@/meta' //import on top        
 * 
 *         
 */
export const extractParsersConfigObject = defineConfigObject<ExtractParsers>(
  _extractParsers.scope,
  _extractParsers.defaults
)


/**
 * Reactive ToConfigRefs of `i18n-ally.extract.parsers`
 */
export const extractParsersConfigs = defineConfigs<ExtractParsers>(
  _extractParsers.scope,
  _extractParsers.defaults
)


/**
 * Config keys of `vue-i18n-ally`
 */
export interface VueI18nAlly {
}

/**
 * Scoped defaults of `vue-i18n-ally`
 */
const _vueI18nAlly = {
/**
 * scope: `vue-i18n-ally`
 */
  scope: "vue-i18n-ally",
/**
 * Keys' defaults of `vue-i18n-ally`
 */
  defaults: {
  } satisfies VueI18nAlly,
}

/**
 * Reactive ConfigObject of `vue-i18n-ally`
 * @example
 * //import { vueI18nAllyConfigObject } from '@/meta' //import on top        
 * 
 *         
 */
export const vueI18nAllyConfigObject = defineConfigObject<VueI18nAlly>(
  _vueI18nAlly.scope,
  _vueI18nAlly.defaults
)


/**
 * Reactive ToConfigRefs of `vue-i18n-ally`
 */
export const vueI18nAllyConfigs = defineConfigs<VueI18nAlly>(
  _vueI18nAlly.scope,
  _vueI18nAlly.defaults
)

