// This file is generated by `vscode-ext-gen`. Do not modify manually.
// @see https://github.com/antfu/vscode-ext-gen

// Meta info
export const publisher = "VSpaceCode"
export const name = "whichkey"
export const version = "0.11.4"
export const displayName = "Which Key"
export const description = "which-key like menu for Visual Studio Code"
export const extensionId = `${publisher}.${name}`

/**
 * Type union of all commands
 */
export type CommandKey = 
  | "whichkey.show"

/**
 * Commands map registed by `VSpaceCode.whichkey`
 */
export const commands = {
  /**
   * Show Menu
   * @value `whichkey.show`
   */
  show: "whichkey.show",
} satisfies Record<string, CommandKey>

/**
 * Type union of all configs
 */
export type ConfigKey = never

export interface ConfigKeyTypeMap {
}

export interface ConfigShorthandMap {
}

export interface ConfigItem<T extends keyof ConfigKeyTypeMap> {
  key: T,
  default: ConfigKeyTypeMap[T],
}


/**
 * Configs map registed by `VSpaceCode.whichkey`
 */
export const configs = {
}

export interface ScopedConfigKeyTypeMap {
}

export const scopedConfigs = {
  scope: "whichkey",
  defaults: {
  } satisfies ScopedConfigKeyTypeMap,
}

