// This file is generated by `vscode-ext-gen`. Do not modify manually.
// @see https://github.com/antfu/vscode-ext-gen

// Meta info
export const publisher = "hoovercj"
export const name = "vscode-power-mode"
export const version = "3.0.2"
export const displayName = "Power Mode"
export const description = "Your code is powerful, unleash it! The extension made popular by Code in the Dark has finally made its way to VS Code."
export const extensionId = `${publisher}.${name}`

/**
 * Type union of all commands
 */
export type CommandKey =
  | "powermode.enablePowerMode"
  | "powermode.disablePowerMode"

/**
 * Commands map registered by `hoovercj.vscode-power-mode`
 */
export const commands = {
  /**
   * Enable Power Mode
   * @value `powermode.enablePowerMode`
   */
  powermodeEnablePowerMode: "powermode.enablePowerMode",
  /**
   * Disable Power Mode
   * @value `powermode.disablePowerMode`
   */
  powermodeDisablePowerMode: "powermode.disablePowerMode",
} satisfies Record<string, CommandKey>

/**
 * Type union of all configs
 */
export type ConfigKey =
  | "powermode.enabled"
  | "powermode.presets"
  | "powermode.combo.location"
  | "powermode.combo.threshold"
  | "powermode.combo.timeout"
  | "powermode.combo.counterEnabled"
  | "powermode.combo.counterSize"
  | "powermode.combo.timerEnabled"
  | "powermode.shake.enabled"
  | "powermode.shake.intensity"
  | "powermode.explosions.enabled"
  | "powermode.explosions.maxExplosions"
  | "powermode.explosions.size"
  | "powermode.explosions.frequency"
  | "powermode.explosions.offset"
  | "powermode.explosions.customExplosions"
  | "powermode.explosions.backgroundMode"
  | "powermode.explosions.gifMode"
  | "powermode.explosions.explosionOrder"
  | "powermode.explosions.duration"
  | "powermode.explosions.customCss"
  | "powermode.comboThreshold"
  | "powermode.comboTimeout"
  | "powermode.enableComboCounter"
  | "powermode.enableComboTimer"
  | "powermode.enableStatusBarComboCounter"
  | "powermode.enableStatusBarComboTimer"
  | "powermode.enableShake"
  | "powermode.shakeIntensity"
  | "powermode.explosionSize"
  | "powermode.explosionFrequency"
  | "powermode.explosionOffset"
  | "powermode.customExplosions"
  | "powermode.backgroundMode"
  | "powermode.gifMode"
  | "powermode.explosionOrder"
  | "powermode.explosionDuration"
  | "powermode.customCss"

export interface ConfigKeyTypeMap {
  "powermode.enabled": boolean,
  "powermode.presets": ("particles" | "fireworks" | "flames" | "magic" | "clippy" | "simple-rift" | "exploding-rift"),
  "powermode.combo.location": ("editor" | "statusbar" | "default" | "off"),
  "powermode.combo.threshold": number,
  "powermode.combo.timeout": number,
  "powermode.combo.counterEnabled": ("show" | "hide" | "default"),
  "powermode.combo.counterSize": number,
  "powermode.combo.timerEnabled": ("show" | "hide" | "default"),
  "powermode.shake.enabled": boolean,
  "powermode.shake.intensity": number,
  "powermode.explosions.enabled": boolean,
  "powermode.explosions.maxExplosions": number,
  "powermode.explosions.size": number,
  "powermode.explosions.frequency": number,
  "powermode.explosions.offset": number,
  "powermode.explosions.customExplosions": unknown[],
  "powermode.explosions.backgroundMode": ("mask" | "image"),
  "powermode.explosions.gifMode": ("continue" | "restart"),
  "powermode.explosions.explosionOrder": unknown,
  "powermode.explosions.duration": number,
  "powermode.explosions.customCss": Record<string, unknown>,
  "powermode.comboThreshold": (unknown | null),
  "powermode.comboTimeout": (unknown | null),
  "powermode.enableComboCounter": (unknown | null),
  "powermode.enableComboTimer": (unknown | null),
  "powermode.enableStatusBarComboCounter": (unknown | null),
  "powermode.enableStatusBarComboTimer": (unknown | null),
  "powermode.enableShake": (unknown | null),
  "powermode.shakeIntensity": (unknown | null),
  "powermode.explosionSize": (unknown | null),
  "powermode.explosionFrequency": (unknown | null),
  "powermode.explosionOffset": (unknown | null),
  "powermode.customExplosions": (unknown | null),
  "powermode.backgroundMode": (unknown | null),
  "powermode.gifMode": (unknown | null),
  "powermode.explosionOrder": (unknown | null),
  "powermode.explosionDuration": (unknown | null),
  "powermode.customCss": (unknown | null),
}

export interface ConfigShorthandMap {
  powermodeEnabled: "powermode.enabled",
  powermodePresets: "powermode.presets",
  powermodeComboLocation: "powermode.combo.location",
  powermodeComboThreshold: "powermode.combo.threshold",
  powermodeComboTimeout: "powermode.combo.timeout",
  powermodeComboCounterEnabled: "powermode.combo.counterEnabled",
  powermodeComboCounterSize: "powermode.combo.counterSize",
  powermodeComboTimerEnabled: "powermode.combo.timerEnabled",
  powermodeShakeEnabled: "powermode.shake.enabled",
  powermodeShakeIntensity: "powermode.shake.intensity",
  powermodeExplosionsEnabled: "powermode.explosions.enabled",
  powermodeExplosionsMaxExplosions: "powermode.explosions.maxExplosions",
  powermodeExplosionsSize: "powermode.explosions.size",
  powermodeExplosionsFrequency: "powermode.explosions.frequency",
  powermodeExplosionsOffset: "powermode.explosions.offset",
  powermodeExplosionsCustomExplosions: "powermode.explosions.customExplosions",
  powermodeExplosionsBackgroundMode: "powermode.explosions.backgroundMode",
  powermodeExplosionsGifMode: "powermode.explosions.gifMode",
  powermodeExplosionsExplosionOrder: "powermode.explosions.explosionOrder",
  powermodeExplosionsDuration: "powermode.explosions.duration",
  powermodeExplosionsCustomCss: "powermode.explosions.customCss",
  powermodeEnableComboCounter: "powermode.enableComboCounter",
  powermodeEnableComboTimer: "powermode.enableComboTimer",
  powermodeEnableStatusBarComboCounter: "powermode.enableStatusBarComboCounter",
  powermodeEnableStatusBarComboTimer: "powermode.enableStatusBarComboTimer",
  powermodeEnableShake: "powermode.enableShake",
  powermodeExplosionSize: "powermode.explosionSize",
  powermodeExplosionFrequency: "powermode.explosionFrequency",
  powermodeExplosionOffset: "powermode.explosionOffset",
  powermodeCustomExplosions: "powermode.customExplosions",
  powermodeBackgroundMode: "powermode.backgroundMode",
  powermodeGifMode: "powermode.gifMode",
  powermodeExplosionOrder: "powermode.explosionOrder",
  powermodeExplosionDuration: "powermode.explosionDuration",
  powermodeCustomCss: "powermode.customCss",
}

export interface ConfigShorthandTypeMap {
  powermodeEnabled: boolean,
  powermodePresets: ("particles" | "fireworks" | "flames" | "magic" | "clippy" | "simple-rift" | "exploding-rift"),
  powermodeComboLocation: ("editor" | "statusbar" | "default" | "off"),
  powermodeComboThreshold: number,
  powermodeComboTimeout: number,
  powermodeComboCounterEnabled: ("show" | "hide" | "default"),
  powermodeComboCounterSize: number,
  powermodeComboTimerEnabled: ("show" | "hide" | "default"),
  powermodeShakeEnabled: boolean,
  powermodeShakeIntensity: number,
  powermodeExplosionsEnabled: boolean,
  powermodeExplosionsMaxExplosions: number,
  powermodeExplosionsSize: number,
  powermodeExplosionsFrequency: number,
  powermodeExplosionsOffset: number,
  powermodeExplosionsCustomExplosions: unknown[],
  powermodeExplosionsBackgroundMode: ("mask" | "image"),
  powermodeExplosionsGifMode: ("continue" | "restart"),
  powermodeExplosionsExplosionOrder: unknown,
  powermodeExplosionsDuration: number,
  powermodeExplosionsCustomCss: Record<string, unknown>,
  powermodeEnableComboCounter: (unknown | null),
  powermodeEnableComboTimer: (unknown | null),
  powermodeEnableStatusBarComboCounter: (unknown | null),
  powermodeEnableStatusBarComboTimer: (unknown | null),
  powermodeEnableShake: (unknown | null),
  powermodeExplosionSize: (unknown | null),
  powermodeExplosionFrequency: (unknown | null),
  powermodeExplosionOffset: (unknown | null),
  powermodeCustomExplosions: (unknown | null),
  powermodeBackgroundMode: (unknown | null),
  powermodeGifMode: (unknown | null),
  powermodeExplosionOrder: (unknown | null),
  powermodeExplosionDuration: (unknown | null),
  powermodeCustomCss: (unknown | null),
}

export interface ConfigItem<T extends keyof ConfigKeyTypeMap> {
  key: T,
  default: ConfigKeyTypeMap[T],
}


/**
 * Configs map registered by `hoovercj.vscode-power-mode`
 */
export const configs = {
  /**
   * Enable to activate POWER MODE!!!
   * @key `powermode.enabled`
   * @default `false`
   * @type `boolean`
   */
  powermodeEnabled: {
    key: "powermode.enabled",
    default: false,
  } as ConfigItem<"powermode.enabled">,
  /**
   * Choose between different preset gifs to use when powermode is activated
   * @key `powermode.presets`
   * @default `"particles"`
   * @type `string`
   */
  powermodePresets: {
    key: "powermode.presets",
    default: "particles",
  } as ConfigItem<"powermode.presets">,
  /**
   * Control where all the combo information is visible.
   * @key `powermode.combo.location`
   * @default `"default"`
   * @type `string`
   */
  powermodeComboLocation: {
    key: "powermode.combo.location",
    default: "default",
  } as ConfigItem<"powermode.combo.location">,
  /**
   * The combo number needed to activate POWER MODE!!! and start shaking and exploding the screen! If the value is 0, POWER MODE will always be active.
   * @key `powermode.combo.threshold`
   * @default `0`
   * @type `number`
   */
  powermodeComboThreshold: {
    key: "powermode.combo.threshold",
    default: 0,
  } as ConfigItem<"powermode.combo.threshold">,
  /**
   * The number of seconds before the combo resets. If the value is 0, the timer will never reset.
   * @key `powermode.combo.timeout`
   * @default `10`
   * @type `number`
   */
  powermodeComboTimeout: {
    key: "powermode.combo.timeout",
    default: 10,
  } as ConfigItem<"powermode.combo.timeout">,
  /**
   * Control whether the combo counter is visible.
   * @key `powermode.combo.counterEnabled`
   * @default `"default"`
   * @type `string`
   */
  powermodeComboCounterEnabled: {
    key: "powermode.combo.counterEnabled",
    default: "default",
  } as ConfigItem<"powermode.combo.counterEnabled">,
  /**
   * Control the size of the Combo Meter text
   * @key `powermode.combo.counterSize`
   * @default `3`
   * @type `number`
   */
  powermodeComboCounterSize: {
    key: "powermode.combo.counterSize",
    default: 3,
  } as ConfigItem<"powermode.combo.counterSize">,
  /**
   * Control whether the combo timer is visible.
   * @key `powermode.combo.timerEnabled`
   * @default `"default"`
   * @type `string`
   */
  powermodeComboTimerEnabled: {
    key: "powermode.combo.timerEnabled",
    default: "default",
  } as ConfigItem<"powermode.combo.timerEnabled">,
  /**
   * Set to false to disable shaking while typing
   * @key `powermode.shake.enabled`
   * @default `true`
   * @type `boolean`
   */
  powermodeShakeEnabled: {
    key: "powermode.shake.enabled",
    default: true,
  } as ConfigItem<"powermode.shake.enabled">,
  /**
   * The intensity with which the screen shakes
   * @key `powermode.shake.intensity`
   * @default `3`
   * @type `number`
   */
  powermodeShakeIntensity: {
    key: "powermode.shake.intensity",
    default: 3,
  } as ConfigItem<"powermode.shake.intensity">,
  /**
   * Set to false to disable explosions while typing
   * @key `powermode.explosions.enabled`
   * @default `true`
   * @type `boolean`
   */
  powermodeExplosionsEnabled: {
    key: "powermode.explosions.enabled",
    default: true,
  } as ConfigItem<"powermode.explosions.enabled">,
  /**
   * The maximum number of simultaneous explosions
   * @key `powermode.explosions.maxExplosions`
   * @default `1`
   * @type `number`
   */
  powermodeExplosionsMaxExplosions: {
    key: "powermode.explosions.maxExplosions",
    default: 1,
  } as ConfigItem<"powermode.explosions.maxExplosions">,
  /**
   * The size of the explosions. For value X, the height is set to X rem and the width to X ch
   * @key `powermode.explosions.size`
   * @default `6`
   * @type `number`
   */
  powermodeExplosionsSize: {
    key: "powermode.explosions.size",
    default: 6,
  } as ConfigItem<"powermode.explosions.size">,
  /**
   * The number of key strokes needed to trigger an explosion. 2 means every second keystroke will explode, 1 means every key stroke.
   * @key `powermode.explosions.frequency`
   * @default `2`
   * @type `number`
   */
  powermodeExplosionsFrequency: {
    key: "powermode.explosions.frequency",
    default: 2,
  } as ConfigItem<"powermode.explosions.frequency">,
  /**
   * The vertical offset of the explosions. Increasing it will move the explosions up, decreasing it will move them down.
   * @key `powermode.explosions.offset`
   * @default `0.35`
   * @type `number`
   */
  powermodeExplosionsOffset: {
    key: "powermode.explosions.offset",
    default: 0.35,
  } as ConfigItem<"powermode.explosions.offset">,
  /**
   *
   * @key `powermode.explosions.customExplosions`
   * @default `[]`
   * @type `array`
   */
  powermodeExplosionsCustomExplosions: {
    key: "powermode.explosions.customExplosions",
    default: [],
  } as ConfigItem<"powermode.explosions.customExplosions">,
  /**
   * Affects the css properties used to display the gif.
   * @key `powermode.explosions.backgroundMode`
   * @default `"mask"`
   * @type `string`
   */
  powermodeExplosionsBackgroundMode: {
    key: "powermode.explosions.backgroundMode",
    default: "mask",
  } as ConfigItem<"powermode.explosions.backgroundMode">,
  /**
   * Control the 'playback' mode of the gifs.
   * @key `powermode.explosions.gifMode`
   * @default `"continue"`
   * @type `string`
   */
  powermodeExplosionsGifMode: {
    key: "powermode.explosions.gifMode",
    default: "continue",
  } as ConfigItem<"powermode.explosions.gifMode">,
  /**
   * Determines how the explosions are cycled. 'random' (default) picks from the list randomly. 'sequential' goes through the list in order, and a number will select the explosion at that (zero based)index in the list
   * @key `powermode.explosions.explosionOrder`
   * @default `"random"`
   * @type `undefined`
   */
  powermodeExplosionsExplosionOrder: {
    key: "powermode.explosions.explosionOrder",
    default: "random",
  } as ConfigItem<"powermode.explosions.explosionOrder">,
  /**
   * Determines how long an explosion lasts (in milliseconds). Set to 0 for it to last forever.
   * @key `powermode.explosions.duration`
   * @default `1000`
   * @type `number`
   */
  powermodeExplosionsDuration: {
    key: "powermode.explosions.duration",
    default: 1000,
  } as ConfigItem<"powermode.explosions.duration">,
  /**
   * Set custom CSS that will apply to the explosion element.
   * @key `powermode.explosions.customCss`
   * @default `{}`
   * @type `object`
   */
  powermodeExplosionsCustomCss: {
    key: "powermode.explosions.customCss",
    default: {},
  } as ConfigItem<"powermode.explosions.customCss">,
  /**
   *
   * @key `powermode.enableComboCounter`
   * @default `null`
   * @type `undefined`
   */
  powermodeEnableComboCounter: {
    key: "powermode.enableComboCounter",
    default: null,
  } as ConfigItem<"powermode.enableComboCounter">,
  /**
   *
   * @key `powermode.enableComboTimer`
   * @default `null`
   * @type `undefined`
   */
  powermodeEnableComboTimer: {
    key: "powermode.enableComboTimer",
    default: null,
  } as ConfigItem<"powermode.enableComboTimer">,
  /**
   * Set to false to disable showing the combo in the statusbar
   * @key `powermode.enableStatusBarComboCounter`
   * @default `null`
   * @type `undefined`
   */
  powermodeEnableStatusBarComboCounter: {
    key: "powermode.enableStatusBarComboCounter",
    default: null,
  } as ConfigItem<"powermode.enableStatusBarComboCounter">,
  /**
   * Set to false to disable showing the timer in the statusbar
   * @key `powermode.enableStatusBarComboTimer`
   * @default `null`
   * @type `undefined`
   */
  powermodeEnableStatusBarComboTimer: {
    key: "powermode.enableStatusBarComboTimer",
    default: null,
  } as ConfigItem<"powermode.enableStatusBarComboTimer">,
  /**
   *
   * @key `powermode.enableShake`
   * @default `null`
   * @type `undefined`
   */
  powermodeEnableShake: {
    key: "powermode.enableShake",
    default: null,
  } as ConfigItem<"powermode.enableShake">,
  /**
   *
   * @key `powermode.explosionSize`
   * @default `null`
   * @type `undefined`
   */
  powermodeExplosionSize: {
    key: "powermode.explosionSize",
    default: null,
  } as ConfigItem<"powermode.explosionSize">,
  /**
   *
   * @key `powermode.explosionFrequency`
   * @default `null`
   * @type `undefined`
   */
  powermodeExplosionFrequency: {
    key: "powermode.explosionFrequency",
    default: null,
  } as ConfigItem<"powermode.explosionFrequency">,
  /**
   *
   * @key `powermode.explosionOffset`
   * @default `null`
   * @type `undefined`
   */
  powermodeExplosionOffset: {
    key: "powermode.explosionOffset",
    default: null,
  } as ConfigItem<"powermode.explosionOffset">,
  /**
   *
   * @key `powermode.customExplosions`
   * @default `null`
   * @type `undefined`
   */
  powermodeCustomExplosions: {
    key: "powermode.customExplosions",
    default: null,
  } as ConfigItem<"powermode.customExplosions">,
  /**
   *
   * @key `powermode.backgroundMode`
   * @default `null`
   * @type `undefined`
   */
  powermodeBackgroundMode: {
    key: "powermode.backgroundMode",
    default: null,
  } as ConfigItem<"powermode.backgroundMode">,
  /**
   *
   * @key `powermode.gifMode`
   * @default `null`
   * @type `undefined`
   */
  powermodeGifMode: {
    key: "powermode.gifMode",
    default: null,
  } as ConfigItem<"powermode.gifMode">,
  /**
   *
   * @key `powermode.explosionOrder`
   * @default `null`
   * @type `undefined`
   */
  powermodeExplosionOrder: {
    key: "powermode.explosionOrder",
    default: null,
  } as ConfigItem<"powermode.explosionOrder">,
  /**
   *
   * @key `powermode.explosionDuration`
   * @default `null`
   * @type `undefined`
   */
  powermodeExplosionDuration: {
    key: "powermode.explosionDuration",
    default: null,
  } as ConfigItem<"powermode.explosionDuration">,
  /**
   *
   * @key `powermode.customCss`
   * @default `null`
   * @type `undefined`
   */
  powermodeCustomCss: {
    key: "powermode.customCss",
    default: null,
  } as ConfigItem<"powermode.customCss">,
}

export interface ScopedConfigKeyTypeMap {
}

export const scopedConfigs = {
  scope: "vscode-power-mode",
  defaults: {
  } satisfies ScopedConfigKeyTypeMap,
}

export interface NestedConfigs {
  "powermode": {
    "enabled": boolean,
    "presets": ("particles" | "fireworks" | "flames" | "magic" | "clippy" | "simple-rift" | "exploding-rift"),
    "combo": {
      "location": ("editor" | "statusbar" | "default" | "off"),
      "threshold": number,
      "timeout": number,
      "counterEnabled": ("show" | "hide" | "default"),
      "counterSize": number,
      "timerEnabled": ("show" | "hide" | "default"),
    },
    "shake": {
      "enabled": boolean,
      "intensity": number,
    },
    "explosions": {
      "enabled": boolean,
      "maxExplosions": number,
      "size": number,
      "frequency": number,
      "offset": number,
      "customExplosions": unknown[],
      "backgroundMode": ("mask" | "image"),
      "gifMode": ("continue" | "restart"),
      "explosionOrder": unknown,
      "duration": number,
      "customCss": Record<string, unknown>,
    },
    "comboThreshold": (unknown | null),
    "comboTimeout": (unknown | null),
    "enableComboCounter": (unknown | null),
    "enableComboTimer": (unknown | null),
    "enableStatusBarComboCounter": (unknown | null),
    "enableStatusBarComboTimer": (unknown | null),
    "enableShake": (unknown | null),
    "shakeIntensity": (unknown | null),
    "explosionSize": (unknown | null),
    "explosionFrequency": (unknown | null),
    "explosionOffset": (unknown | null),
    "customExplosions": (unknown | null),
    "backgroundMode": (unknown | null),
    "gifMode": (unknown | null),
    "explosionOrder": (unknown | null),
    "explosionDuration": (unknown | null),
    "customCss": (unknown | null),
  },
}

export interface NestedScopedConfigs {
}

