// This file is generated by `vscode-ext-gen`. Do not modify manually.
// @see https://github.com/antfu/vscode-ext-gen

// Meta info
export const publisher = "tonybaloney"
export const name = "vscode-pets"
export const version = "1.34.0"
export const displayName = "vscode-pets"
export const description = "Pets for your VS Code"
export const extensionId = `${publisher}.${name}`

/**
 * Type union of all commands
 */
export type CommandKey =
  | "vscode-pets.start"
  | "vscode-pets.throw-with-mouse"
  | "vscode-pets.throw-ball"
  | "vscode-pets.export-pet-list"
  | "vscode-pets.import-pet-list"
  | "vscode-pets.spawn-pet"
  | "vscode-pets.delete-pet"
  | "vscode-pets.remove-all-pets"
  | "vscode-pets.roll-call"

/**
 * Commands map registered by `tonybaloney.vscode-pets`
 */
export const commands = {
  /**
   * ペットコーディングセッションを開始
   * @value `vscode-pets.start`
   */
  start: "vscode-pets.start",
  /**
   * マウスでボールを投げる
   * @value `vscode-pets.throw-with-mouse`
   */
  throwWithMouse: "vscode-pets.throw-with-mouse",
  /**
   * ボールを投げる
   * @value `vscode-pets.throw-ball`
   */
  throwBall: "vscode-pets.throw-ball",
  /**
   * ペットリストをエクスポート
   * @value `vscode-pets.export-pet-list`
   */
  exportPetList: "vscode-pets.export-pet-list",
  /**
   * ペットリストをインポート
   * @value `vscode-pets.import-pet-list`
   */
  importPetList: "vscode-pets.import-pet-list",
  /**
   * ペットを生成
   * @value `vscode-pets.spawn-pet`
   */
  spawnPet: "vscode-pets.spawn-pet",
  /**
   * ペットを削除
   * @value `vscode-pets.delete-pet`
   */
  deletePet: "vscode-pets.delete-pet",
  /**
   * すべてのペットを削除
   * @value `vscode-pets.remove-all-pets`
   */
  removeAllPets: "vscode-pets.remove-all-pets",
  /**
   * 点呼
   * @value `vscode-pets.roll-call`
   */
  rollCall: "vscode-pets.roll-call",
} satisfies Record<string, CommandKey>

/**
 * Type union of all configs
 */
export type ConfigKey =
  | "vscode-pets.petColor"
  | "vscode-pets.petType"
  | "vscode-pets.petSize"
  | "vscode-pets.position"
  | "vscode-pets.theme"
  | "vscode-pets.throwBallWithMouse"
  | "vscode-pets.disableEffects"

export interface ConfigKeyTypeMap {
  "vscode-pets.petColor": ("black" | "lightbrown" | "brown" | "green" | "yellow" | "gray" | "purple" | "red" | "white" | "orange" | "akita" | "socks black" | "socks beige" | "socks brown" | "paint beige" | "paint black" | "paint brown" | "magical" | "warrior" | "pink"),
  "vscode-pets.petType": ("cat" | "chicken" | "crab" | "clippy" | "cockatiel" | "dog" | "fox" | "frog" | "horse" | "mod" | "rat" | "rocky" | "rubber-duck" | "snake" | "squirrel" | "totoro" | "turtle" | "zappy" | "snail" | "bunny" | "skeleton" | "deno" | "morph" | "panda"),
  "vscode-pets.petSize": ("nano" | "small" | "medium" | "large"),
  "vscode-pets.position": ("panel" | "explorer"),
  "vscode-pets.theme": ("none" | "forest" | "castle" | "beach" | "winter" | "autumn"),
  "vscode-pets.throwBallWithMouse": boolean,
  "vscode-pets.disableEffects": boolean,
}

export interface ConfigShorthandMap {
  petColor: "vscode-pets.petColor",
  petType: "vscode-pets.petType",
  petSize: "vscode-pets.petSize",
  position: "vscode-pets.position",
  theme: "vscode-pets.theme",
  throwBallWithMouse: "vscode-pets.throwBallWithMouse",
  disableEffects: "vscode-pets.disableEffects",
}

export interface ConfigShorthandTypeMap {
  petColor: ("black" | "lightbrown" | "brown" | "green" | "yellow" | "gray" | "purple" | "red" | "white" | "orange" | "akita" | "socks black" | "socks beige" | "socks brown" | "paint beige" | "paint black" | "paint brown" | "magical" | "warrior" | "pink"),
  petType: ("cat" | "chicken" | "crab" | "clippy" | "cockatiel" | "dog" | "fox" | "frog" | "horse" | "mod" | "rat" | "rocky" | "rubber-duck" | "snake" | "squirrel" | "totoro" | "turtle" | "zappy" | "snail" | "bunny" | "skeleton" | "deno" | "morph" | "panda"),
  petSize: ("nano" | "small" | "medium" | "large"),
  position: ("panel" | "explorer"),
  theme: ("none" | "forest" | "castle" | "beach" | "winter" | "autumn"),
  throwBallWithMouse: boolean,
  disableEffects: boolean,
}

export interface ConfigItem<T extends keyof ConfigKeyTypeMap> {
  key: T,
  default: ConfigKeyTypeMap[T],
}


/**
 * Configs map registered by `tonybaloney.vscode-pets`
 */
export const configs = {
  /**
   * ペットの色
   * @key `vscode-pets.petColor`
   * @default `"brown"`
   * @type `string`
   */
  petColor: {
    key: "vscode-pets.petColor",
    default: "brown",
  } as ConfigItem<"vscode-pets.petColor">,
  /**
   * ペットの種類
   * @key `vscode-pets.petType`
   * @default `"cat"`
   * @type `string`
   */
  petType: {
    key: "vscode-pets.petType",
    default: "cat",
  } as ConfigItem<"vscode-pets.petType">,
  /**
   * ペットのサイズ
   * @key `vscode-pets.petSize`
   * @default `"nano"`
   * @type `string`
   */
  petSize: {
    key: "vscode-pets.petSize",
    default: "nano",
  } as ConfigItem<"vscode-pets.petSize">,
  /**
   * ペットパネルの位置
   * @key `vscode-pets.position`
   * @default `"explorer"`
   * @type `string`
   */
  position: {
    key: "vscode-pets.position",
    default: "explorer",
  } as ConfigItem<"vscode-pets.position">,
  /**
   * テーマ
   * @key `vscode-pets.theme`
   * @default `"none"`
   * @type `string`
   */
  theme: {
    key: "vscode-pets.theme",
    default: "none",
  } as ConfigItem<"vscode-pets.theme">,
  /**
   * マウスでボールを投げる
   * @key `vscode-pets.throwBallWithMouse`
   * @default `false`
   * @type `boolean`
   */
  throwBallWithMouse: {
    key: "vscode-pets.throwBallWithMouse",
    default: false,
  } as ConfigItem<"vscode-pets.throwBallWithMouse">,
  /**
   * エフェクトを無効にする
   * @key `vscode-pets.disableEffects`
   * @default `false`
   * @type `boolean`
   */
  disableEffects: {
    key: "vscode-pets.disableEffects",
    default: false,
  } as ConfigItem<"vscode-pets.disableEffects">,
}

export interface ScopedConfigKeyTypeMap {
  "petColor": ("black" | "lightbrown" | "brown" | "green" | "yellow" | "gray" | "purple" | "red" | "white" | "orange" | "akita" | "socks black" | "socks beige" | "socks brown" | "paint beige" | "paint black" | "paint brown" | "magical" | "warrior" | "pink"),
  "petType": ("cat" | "chicken" | "crab" | "clippy" | "cockatiel" | "dog" | "fox" | "frog" | "horse" | "mod" | "rat" | "rocky" | "rubber-duck" | "snake" | "squirrel" | "totoro" | "turtle" | "zappy" | "snail" | "bunny" | "skeleton" | "deno" | "morph" | "panda"),
  "petSize": ("nano" | "small" | "medium" | "large"),
  "position": ("panel" | "explorer"),
  "theme": ("none" | "forest" | "castle" | "beach" | "winter" | "autumn"),
  "throwBallWithMouse": boolean,
  "disableEffects": boolean,
}

export const scopedConfigs = {
  scope: "vscode-pets",
  defaults: {
    "petColor": "brown",
    "petType": "cat",
    "petSize": "nano",
    "position": "explorer",
    "theme": "none",
    "throwBallWithMouse": false,
    "disableEffects": false,
  } satisfies ScopedConfigKeyTypeMap,
}

export interface NestedConfigs {
  "vscode-pets": {
    "petColor": ("black" | "lightbrown" | "brown" | "green" | "yellow" | "gray" | "purple" | "red" | "white" | "orange" | "akita" | "socks black" | "socks beige" | "socks brown" | "paint beige" | "paint black" | "paint brown" | "magical" | "warrior" | "pink"),
    "petType": ("cat" | "chicken" | "crab" | "clippy" | "cockatiel" | "dog" | "fox" | "frog" | "horse" | "mod" | "rat" | "rocky" | "rubber-duck" | "snake" | "squirrel" | "totoro" | "turtle" | "zappy" | "snail" | "bunny" | "skeleton" | "deno" | "morph" | "panda"),
    "petSize": ("nano" | "small" | "medium" | "large"),
    "position": ("panel" | "explorer"),
    "theme": ("none" | "forest" | "castle" | "beach" | "winter" | "autumn"),
    "throwBallWithMouse": boolean,
    "disableEffects": boolean,
  },
}

export interface NestedScopedConfigs {
  "petColor": ("black" | "lightbrown" | "brown" | "green" | "yellow" | "gray" | "purple" | "red" | "white" | "orange" | "akita" | "socks black" | "socks beige" | "socks brown" | "paint beige" | "paint black" | "paint brown" | "magical" | "warrior" | "pink"),
  "petType": ("cat" | "chicken" | "crab" | "clippy" | "cockatiel" | "dog" | "fox" | "frog" | "horse" | "mod" | "rat" | "rocky" | "rubber-duck" | "snake" | "squirrel" | "totoro" | "turtle" | "zappy" | "snail" | "bunny" | "skeleton" | "deno" | "morph" | "panda"),
  "petSize": ("nano" | "small" | "medium" | "large"),
  "position": ("panel" | "explorer"),
  "theme": ("none" | "forest" | "castle" | "beach" | "winter" | "autumn"),
  "throwBallWithMouse": boolean,
  "disableEffects": boolean,
}

